const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const SESSION_KEY = 'qianji.demo.currentSession.v2';
const FORMAL_KEY = 'qianji.demo.formalReviews.v2';
const TASK_KEY = 'qianji.demo.reviewTasks.v2';
const currentShop = {id:'cos-official',name:'COS官方旗舰店'};

const labels = ['品牌', '面料', '场景', '利益点', '促单', '其他'];
const baseAsr = {
  品牌: ['“这是今天要讲的这个系列。”','“品牌这一代主要调整了脚感。”','“之前穿过同系列的可以对比。”','“这个系列定位是日常通勤。”','“今天同系列会放在一起讲。”'],
  面料: ['“面料表面的纹理近看一下。”','“这一块摸起来不是硬的。”','“侧面这里有支撑结构。”','“内里接触皮肤的位置是软的。”','“材质信息以商品详情页为准。”','“我把细节拿近一点给你们看。”'],
  场景: ['“日常上班穿可以。”','“周末出去走路也适合。”','“配浅色下装会更显层次。”','“通勤时间长的可以看一下。”','“室内和户外都能搭。”','“旅行走路多也可以考虑。”'],
  利益点: ['“今天按商品页显示价格。”','“赠品条件以商品卡为准。”','“有无运费险看页面实际显示。”','“库存和尺码以链接为准。”','“下单前先核对颜色和规格。”'],
  促单: ['“需要的先把尺码选好。”','“喜欢这个颜色可以先加购。”','“确认商品页信息后再拍。”','“库存数量以商品卡刷新为准。”','“这一轮结束会讲下一个款。”','“想看细节的现在可以留言。”'],
  其他: ['“评论区我看一下。”','“镜头往下给一点。”','“等一下我拿另一件。”','“这个问题稍后回答。”','“我们继续往下讲。”']
};
const refundAsr = {
  尺码: ['“尺码先按商品页尺码表核对。”','“脚背高的不要只按平时尺码选。”','“我报的身高体重只作试穿参考。”','“介于两个尺码之间先看脚宽。”','“不同脚型上脚感受会有差异。”','“拍之前再确认一次尺码。”','“尺码建议以详情页标注为准。”','“不确定的先咨询客服再下单。”'],
  版型: ['“这个版型前掌空间不算特别宽。”','“上身轮廓是偏直的。”','“喜欢宽松感需要结合尺寸表。”','“侧面收窄位置给你们看一下。”','“不同身材穿着效果会不同。”','“版型信息不要只看镜头远景。”'],
  穿着体验: ['“我现在试穿的感受是包裹感明显。”','“刚穿和走一段时间感受可能不同。”','“脚感体验因人而异。”','“长时间穿着建议结合自己的脚型。”','“这里说的是主播本人试穿感受。”'],
  功能承诺: ['“具体功能以商品详情页说明为准。”','“防护能力不要超出页面说明理解。”','“我这里只演示日常穿着。”','“不同环境下效果会有差异。”','“不能把日常体验当专业测试结果。”','“页面没有写的功能我不做承诺。”','“使用前请看商品说明。”'],
  利益承诺: ['“赠品达到页面条件才会带出。”','“运费险以你们页面实际显示为准。”','“价格以结算页为准。”','“售后范围按平台规则执行。”']
};

const demoSessions = {
  comprehensive: {
    name:'综合异常场', info:{title:'秋冬上新专场',date:'2026-09-07',start:'13:00',end:'18:36',duration:'5小时36分',host:'小福',operator:'陈晨'},
    reviewItems:[
      {id:'opening',type:'anomaly',category:'opening',detailView:'opening',title:'开播15分钟出单偏慢',timeRange:'13:00–13:15',current:'18单',compare:'同主播近7场平均24单',difference:'低25%',button:'同屏复盘'},
      {id:'paid',type:'anomaly',category:'paid',detailView:'paid',title:'付费消耗上涨，但成交下降',timeRange:'16:32–16:52',current:'投放消耗 +31%',compare:'付费成交金额 -18%',difference:'走势背离',button:'分钟级复盘'},
      {id:'cvr89',type:'anomaly',category:'product_cvr',detailView:'product',productId:'89ZP',title:'89ZP 点击成交转化偏低',timeRange:'17:04–17:40',current:'本次2.10%',compare:'今年前6次平均3.40%',difference:'低38%',button:'商品复盘'}
    ],
    opening:{product:'8NRQ',current:{orders:18,exposure:6900,clicks:857,ctr:12.42,cvr:2.10,time:'13:00–13:15'},compare:{label:'同商品同主播历史较好开场',orders:31,exposure:6000,clicks:886,ctr:14.77,cvr:3.50,time:'2026-08-31 13:00–13:15'},talk:{current:[25,22,13,16,14,10],compare:[16,20,24,18,16,6]}},
    paid:{time:'16:32–16:52',summary:{beforeSpend:100,anomalySpend:131,beforeGmv:1000,anomalyGmv:820},events:[],times:['16:20','16:24','16:28','16:32','16:36','16:40','16:44','16:48','16:52','16:56'],gmv:[980,1080,1120,1070,940,820,760,700,780,920],spend:[31,33,34,36,42,48,53,58,61,57],talk:{current:[17,19,29,14,11,10],compare:[15,18,20,22,19,6]}},
    products:{cvr89:{product:'89ZP 黑色',time:'17:04–17:40',exposure:2757,clicks:429,orders:9,refunds:1,rates:{ctr:15.56,cvr:2.10,refund:11.11},compare:{label:'该商品今年前6次讲解平均',ctr:15.10,cvr:3.40,refund:10.80},focus:'cvr',factors:[['价格','¥899','¥899','一致'],['赠品','满899赠帆布袋','满899赠袜子+帆布袋','条件不同']],talk:{current:[16,20,23,16,10,15],compare:[15,20,22,20,14,9]}}},
    report:{strategy:'本场以8NRQ作为开场主推，复盘聚焦开场承接、付费成交背离与89ZP成交转化。',bullets:{opening:'开场15分钟18单，低于同主播近7场平均24单；场景主标签占比低于同商品历史较好开场，仍需结合录屏确认。',paid:'16:32–16:52投放消耗增加31%，付费成交金额下降18%；该时段没有已记录的商品、价格或投放策略操作。',cvr89:'89ZP曝光点击率15.56%接近历史15.10%，点击成交率2.10%低于历史3.40%；价格一致，赠品条件不同。'},actions:{opening:'下场补足8NRQ开场场景表达并继续观察前15分钟。',paid:'验证利益点和促单表达调整，保持投放口径不变后比较。',cvr89:'继续验证89ZP赠品条件与促单话术。'}},
    hostReport:'<h3>一、表现较好的部分</h3><p>89ZP材质和商品页规则表达谨慎，可继续保留。</p><h3>二、需要调整的部分</h3><p>付费背离时段利益点和促单主标签减少，下场优先验证表达完整度。</p><h3>三、讲解状态</h3><p>本场没有把主播状态作为独立异常。</p><h3>四、下场练习重点</h3><p>8NRQ开场补充具体场景；89ZP只按商品页实际规则说明权益。</p>',
    tasks:[{task:'补足8NRQ开场场景表达',owner:'主播 小福',deadline:'下场前'},{task:'验证付费背离时段话术调整',owner:'',deadline:''},{task:'验证89ZP赠品条件及促单话术',owner:'运营 陈晨',deadline:''}]
  },
  productCtr:{
    name:'商品点击偏低场',info:{title:'深灰通勤主题场',date:'2026-09-08',start:'14:00',end:'18:20',duration:'4小时20分',host:'安安',operator:'陈晨'},
    reviewItems:[{id:'ctr6',type:'anomaly',category:'product_ctr',detailView:'product',productId:'6T2M',title:'6T2M 曝光点击率偏低',timeRange:'15:18–15:46',current:'本次8.3%',compare:'今年前5次平均13.1%',difference:'低37%',button:'商品复盘'}],
    products:{ctr6:{product:'6T2M 深灰',time:'15:18–15:46',exposure:8600,clicks:714,orders:33,refunds:2,rates:{ctr:8.30,cvr:4.62,refund:6.06},compare:{label:'该商品今年前5次讲解平均',ctr:13.10,cvr:4.40,refund:6.20},focus:'ctr',factors:[['穿搭','深灰上衣 + 深色下装','深灰上衣 + 米白下装','整体层次不同'],['商品主图','当前主图 A','历史表现较好主图 B','版本不同']],talk:{current:[16,22,12,18,16,16],compare:[15,20,24,18,15,8]}}},
    report:{strategy:'本场6T2M曝光规模正常，系统只将曝光到点击环节列为复盘重点。',bullets:{ctr6:'6T2M曝光8,600，曝光点击率8.3%，低于前5次13.1%；点击成交率4.62%与历史4.40%接近。当前穿搭、主图版本和场景表达存在差异，但不直接作为原因。'},actions:{ctr6:'下场分别验证浅色下装搭配、主图B与场景表达，避免多因素同时变化。'}},
    hostReport:'<h3>一、表现较好的部分</h3><p>用户点击后的成交承接保持在正常范围。</p><h3>二、需要调整的部分</h3><p>本次场景表达占比减少，展示时补充浅色下装对比和完整穿搭。</p><h3>三、讲解状态</h3><p>话术结构存在明显差异，本场优先复盘表达与展示，不继续推断主播状态。</p><h3>四、下场练习重点</h3><p>按“整体穿搭—面料近景—具体场景”顺序完成一次完整展示。</p>',tasks:[{task:'准备6T2M浅色下装对比穿搭',owner:'运营 陈晨',deadline:'下场前'},{task:'验证主图B单变量效果',owner:'',deadline:''}]
  },
  hostState:{
    name:'话术相近但主播状态变化场',info:{title:'8NRQ返场专场',date:'2026-09-08',start:'19:00',end:'23:10',duration:'4小时10分',host:'小福',operator:'林晓'},
    reviewItems:[{id:'state8',type:'anomaly',category:'product_cvr',detailView:'product',productId:'8NRQ',title:'8NRQ 点击成交转化偏低',timeRange:'20:12–20:44',current:'本次2.7%',compare:'同商品同主播近5次4.1%',difference:'低34%',button:'商品复盘'}],
    products:{state8:{product:'8NRQ',time:'20:12–20:44',exposure:7600,clicks:1140,orders:31,refunds:2,rates:{ctr:15.00,cvr:2.72,refund:6.45},compare:{label:'同商品同主播近5次平均',ctr:15.20,cvr:4.10,refund:6.30},focus:'cvr',factors:[['价格','¥899','¥899','一致'],['赠品','满899赠帆布袋','满899赠帆布袋','一致']],talk:{current:[16,21,22,19,14,8],compare:[15,20,23,20,14,8]},hostState:{speed:535,speedCompare:455,db:81,dbCompare:73,emotion:'节奏偏紧',confidence:65}}},
    report:{strategy:'本场8NRQ价格、赠品和话术结构均与同商品同主播历史表现接近，业务结果仍有差异。',bullets:{state8:'点击成交率2.72%，低于近5次4.10%；主标签最大差异仅1个百分点，因此继续查看状态数据：语速高17.6%，分贝高8dB。情绪结果仅作辅助。'},actions:{state8:'下场保持价格、赠品和话术结构不变，结合录屏验证讲解节奏。'}},
    hostReport:'<h3>一、表现较好的部分</h3><p>主标签结构与历史表现较好讲解接近。</p><h3>二、需要调整的部分</h3><p>不把转化变化直接归因给主播，先结合录屏确认节奏是否影响信息接收。</p><h3>三、讲解状态</h3><p>本次语速535字/分钟，近5次455；分贝81dB，近5次73dB。辅助识别“节奏偏紧”65%，不作为原因结论。</p><h3>四、下场练习重点</h3><p>保持话术内容不变，复盘讨论明确下一场关注语速与停顿节奏。</p>',tasks:[{task:'保持话术不变并验证讲解节奏',owner:'主播 小福',deadline:'下场前'}]
  },
  refund:{
    name:'退款率异常场',info:{title:'7K3Q功能款专场',date:'2026-09-09',start:'13:30',end:'17:45',duration:'4小时15分',host:'安安',operator:'陈晨'},
    reviewItems:[{id:'refund7',type:'anomaly',category:'refund',detailView:'product',productId:'7K3Q',title:'7K3Q 退款率偏高',timeRange:'15:10–15:42',current:'本次25%',compare:'今年前8次平均12%',difference:'高13个百分点',button:'商品复盘'}],
    products:{refund7:{product:'7K3Q',time:'15:10–15:42',exposure:3500,clicks:560,orders:28,refunds:7,rates:{ctr:16,cvr:5,refund:25},compare:{label:'该商品今年前8次讲解平均',ctr:15.4,cvr:4.8,refund:12},focus:'refund',talk:{current:[12,18,24,19,17,10]}}},
    report:{strategy:'本场7K3Q曝光点击与点击成交正常，退款率被识别为需要人工复盘的环节。',bullets:{refund7:'本次退款率25%，高于前8次平均12%。当前无法取得退款用户画像，也无法确认退款用户听过哪些话术；仅回看本次商品讲解中的尺码、版型、体验和承诺表达。'},actions:{refund7:'人工核对7K3Q相关表达是否超出商品页信息，并继续观察后续退款数据。'}},
    hostReport:'<h3>一、表现较好的部分</h3><p>曝光点击和点击成交处于正常范围。</p><h3>二、需要调整的部分</h3><p>与运营共同回看本次讲解中的尺码、版型、穿着体验和功能承诺原话。</p><h3>三、讲解状态</h3><p>本场没有满足继续展开主播状态的条件。</p><h3>四、下场练习重点</h3><p>只按商品页事实描述功能、权益和适用范围，不根据退款用户做未经支持的推断。</p>',tasks:[{task:'核对7K3Q尺码与功能承诺原话',owner:'主播 安安',deadline:'下场前'}]
  },
  opportunity:{
    name:'机会款发现场',info:{title:'秋季机会款测试场',date:'2026-09-09',start:'14:30',end:'18:30',duration:'4小时',host:'小福',operator:'林晓'},
    reviewItems:[{id:'opp8',type:'opportunity',category:'opportunity_product',detailView:'product',productId:'8DF0',title:'8DF0绿色低曝光下转化表现突出',timeRange:'15:56–16:24',current:'曝光1,260',compare:'点击率18.7% · 成交率5.6%',difference:'值得继续验证',button:'查看机会'}],
    events:[{time:'15:56',label:'切换主推商品',detail:'8NRQ → 8DF0绿色'}],
    minuteTrend:{times:['15:48','15:50','15:52','15:54','15:56','15:58','16:00','16:02','16:04','16:06','16:08'],exposure:[96,102,98,105,112,128,141,155,162,170,181],clicks:[10,11,9,12,18,22,27,30,31,33,36],eventIndex:4},
    products:{opp8:{product:'8DF0绿色',time:'15:56–16:24',exposure:1260,clicks:236,orders:13,refunds:1,rates:{ctr:18.73,cvr:5.51,refund:7.69},compare:{label:'该商品近期平均',ctr:12.40,cvr:3.80,refund:7.50},focus:'opportunity',shortVideo:{exposure:8300,label:'近期短视频曝光'},talk:{current:[14,20,25,21,14,6],compare:[15,19,22,20,16,8]}}},
    report:{strategy:'本场在15:56实际切换主推商品至8DF0绿色，系统将其识别为值得继续验证的机会，不判断为爆款。',bullets:{opp8:'8DF0绿色曝光1,260，曝光点击率18.73%高于近期12.40%，点击成交率5.51%高于近期3.80%；近期短视频曝光8,300。当前曝光样本仍小，事件与结果只作关联观察。'},actions:{opp8:'下一场适度增加8DF0绿色讲解与曝光，继续验证转化稳定性。'}},
    hostReport:'<h3>一、表现较好的部分</h3><p>8DF0绿色场景和利益点表达结构完整，可作为下一场保持的讲解版本。</p><h3>二、需要调整的部分</h3><p>当前没有证据要求大幅改话术。</p><h3>三、讲解状态</h3><p>无需展开主播状态。</p><h3>四、下场练习重点</h3><p>保持本次表达顺序，在增加曝光后继续观察；不要把一场低样本表现理解为已经验证成功。</p>',tasks:[{task:'下一场增加8DF0绿色验证量',owner:'运营 林晓',deadline:''}]
  },
  newProduct:{
    name:'新款首播场',info:{title:'8PBT新品首播',date:'2026-09-10',start:'12:00',end:'16:00',duration:'4小时',host:'安安',operator:'陈晨'},
    reviewItems:[{id:'new8',type:'observation',category:'new_product',detailView:'product',productId:'8PBT',title:'8PBT 首播表现记录',timeRange:'12:36–13:18',current:'两轮讲解成交5件',compare:'暂无同款历史销售数据',difference:'待观察',button:'查看首播'}],
    products:{new8:{product:'8PBT新款',time:'12:36–13:18',exposure:1620,clicks:145,orders:5,refunds:0,rates:{ctr:8.95,cvr:3.45,refund:0},compare:null,focus:'new',history:{thisYearSales:0,lastYearSameProduct:false},rounds:2,prelaunch:{exposure:1486,clicks:126,orders:5,ctr:8.48,cvr:3.97},colors:[['灰色',4],['其他颜色',1]],talk:{current:[17,24,20,16,12,11]}}},
    report:{strategy:'8PBT为今年首次正式销售，去年无同款记录；本场主要建立首场表现记录，不判断异常。',bullets:{new8:'本场两轮讲解成交5件，其中灰色4件、其他颜色1件。前置挂链曝光1,486、点击126、成交5；样本较少，仅作辅助记录。'},actions:{new8:'继续积累后续场次数据，形成稳定历史后再做趋势判断。'}},
    hostReport:'<h3>一、表现较好的部分</h3><p>完成两轮相对完整的新款讲解，并形成可追踪的首场记录。</p><h3>二、需要调整的部分</h3><p>当前没有足够历史样本判断话术优劣。</p><h3>三、讲解状态</h3><p>不因单场数据展开状态判断。</p><h3>四、下场练习重点</h3><p>继续使用稳定讲解结构积累数据，不根据首场5件成交过早归因。</p>',tasks:[{task:'继续积累8PBT后续场次数据',owner:'',deadline:''}]
  }
};

/* The six earlier demo cases are consolidated into one coherent five-hour session.
   Production does not have "demo types": rules emit reviewItems for a real session. */
function clone(value){return JSON.parse(JSON.stringify(value));}
const caseCtr=clone(demoSessions.productCtr),caseRefund=clone(demoSessions.refund),caseOpportunity=clone(demoSessions.opportunity),caseNew=clone(demoSessions.newProduct);
const mainSession=demoSessions.comprehensive;
const ctr6=caseCtr.products.ctr6;ctr6.time='14:05–14:28';
const new8=caseNew.products.new8;new8.time='14:50–15:12';
const opp8=caseOpportunity.products.opp8;opp8.time='15:56–16:18';
const refund7=caseRefund.products.refund7;refund7.time='17:48–18:15';
mainSession.name='综合主演示场';
mainSession.products={...mainSession.products,ctr6,new8,opp8,refund7,
  linked8:{product:'8P6A挂链商品',time:'13:32–13:55',exposure:960,clicks:142,orders:8,naturalOrders:4,rates:{ctr:14.79,cvr:5.63},shortVideo:{exposure:6100,label:'近期短视频曝光'},focus:'linked_opportunity'},
  linked9:{product:'9R2Q挂链商品',time:'18:18–18:32',exposure:420,clicks:38,orders:1,naturalOrders:1,rates:{ctr:9.05,cvr:2.63},focus:'linked_observation'}
};
mainSession.events=[{time:'15:56',label:'切换主推商品',detail:'8NRQ → 8DF0绿色'}];
mainSession.minuteTrend={...caseOpportunity.minuteTrend};
mainSession.paid.talk={current:[15,19,21,20,17,8],compare:[15,18,20,21,18,8]};
mainSession.paid.hostState={speed:535,speedCompare:455,db:81,dbCompare:73,emotion:'节奏偏紧',confidence:65};
mainSession.reviewItems=[
  {id:'opening',type:'anomaly',category:'opening',detailView:'opening',title:'开播15分钟出单偏慢',timeRange:'13:00–13:15',current:'18单',compare:'同主播近7场平均24单',difference:'低25%',button:'同屏复盘',relatedMetrics:['gmv','exposure']},
  {id:'linked8',type:'opportunity',category:'linked_product_opportunity',detailView:'linked_product',productId:'8P6A',productName:'8P6A挂链商品',isExplained:false,displayMode:'linked_only_opportunity',title:'8P6A 挂链未讲解但自然成交起量',timeRange:'13:32–13:55',current:'自然成交4件',compare:'本场曝光960 · 点击142',difference:'值得增加讲解验证',button:'查看挂链机会',relatedMetrics:['exposure','productCtr']},
  {id:'ctr6',type:'anomaly',category:'product_ctr',detailView:'product',productId:'6T2M',productName:'6T2M 深灰',isExplained:true,displayMode:'explained_product',title:'6T2M 曝光点击率偏低',timeRange:'14:05–14:28',current:'本次8.3%',compare:'今年前5次平均13.1%',difference:'低37%',button:'商品复盘',relatedMetrics:['productCtr','exposure']},
  {id:'new8',type:'observation',category:'new_product',detailView:'product',productId:'8PBT',productName:'8PBT新款',isExplained:true,displayMode:'explained_product',title:'8PBT 新品首次讲解',timeRange:'14:50–15:12',current:'两轮讲解成交5件',compare:'暂无同款历史销售数据',difference:'待观察',button:'查看首播',relatedMetrics:['exposure','productCtr']},
  {id:'opp8',type:'opportunity',category:'opportunity_product',detailView:'product',productId:'8DF0',productName:'8DF0绿色',isExplained:true,displayMode:'explained_product',title:'8DF0绿色低曝光下转化突出',timeRange:'15:56–16:18',current:'曝光1,260',compare:'点击率18.7% · 成交率5.6%',difference:'值得继续验证',button:'查看机会',relatedMetrics:['productCtr','productCvr'],relatedItemIds:['operation-switch']},
  {id:'paid',type:'anomaly',category:'paid',detailView:'paid',productId:'89ZP',title:'付费消耗上涨，但付费成交下降',timeRange:'16:32–16:52',current:'投放消耗 +31%',compare:'付费成交金额 -18%',difference:'出现明显背离',button:'分钟级复盘',relatedMetrics:['gmv','spend'],relatedItemIds:['state-evidence','product-context']},
  {id:'cvr89',type:'anomaly',category:'product_cvr',detailView:'product',productId:'89ZP',productName:'89ZP 黑色',isExplained:true,displayMode:'explained_product',title:'89ZP 点击成交转化偏低',timeRange:'17:04–17:40',current:'本次2.10%',compare:'今年前6次平均3.40%',difference:'低38%',button:'商品复盘',relatedMetrics:['productCtr','productCvr']},
  {id:'refund7',type:'anomaly',category:'refund',detailView:'product',productId:'7K3Q',productName:'7K3Q',isExplained:true,displayMode:'explained_product',title:'7K3Q 退款率偏高',timeRange:'17:48–18:15',current:'本次25%',compare:'今年前8次平均12%',difference:'高13个百分点',button:'商品复盘',relatedMetrics:['refundRate','orders']},
  {id:'linked9',type:'observation',category:'linked_product_observation',detailView:'linked_product',productId:'9R2Q',productName:'9R2Q挂链商品',isExplained:false,displayMode:'linked_only_observation',title:'9R2Q 挂链未讲解，当前样本较少',timeRange:'18:18–18:32',current:'曝光420 · 成交1件',compare:'暂无讲解段',difference:'待观察',button:'查看挂链表现',relatedMetrics:['exposure','productCtr']},
  {id:'operation-switch',type:'event',category:'operation_event',lane:'operation',title:'切换主推商品：8NRQ → 8DF0绿色',shortTitle:'切换主推8DF0',startTime:'15:56',endTime:'15:56',timeRange:'15:56',current:'8NRQ → 8DF0绿色',detailType:'event',detailTargetId:'opp8',relatedItemIds:['opp8'],relatedMetrics:[]},
  {id:'state-evidence',type:'event',category:'talk_evidence',lane:'talk_state',title:'话术结构接近，语速与分贝明显升高',shortTitle:'讲解节奏升高',startTime:'16:34',endTime:'16:41',timeRange:'16:34–16:41',current:'语速535字/分钟 · 分贝81dB',compare:'同商品同主播近5次455字/分钟 · 73dB',difference:'同期状态变化',detailType:'paid',detailTargetId:'paid',relatedItemIds:['paid'],relatedMetrics:['gmv','spend']},
  {id:'product-context',type:'event',category:'product_context',lane:'product',productId:'89ZP',title:'该时段当前讲解商品：89ZP',shortTitle:'89ZP讲解中',startTime:'16:32',endTime:'16:52',timeRange:'16:32–16:52',current:'89ZP讲解中',detailType:'paid',detailTargetId:'paid',relatedItemIds:['paid'],relatedMetrics:['gmv','spend']}
];
mainSession.report={
  strategy:'本场以8NRQ开场，随后依次完成6T2M、8PBT、8DF0绿色、89ZP与7K3Q讲解；8P6A与9R2Q仅挂链未讲解，因此只作为机会或待观察提示，不进入商品异常。',
  bullets:{
    opening:'开场15分钟18单，低于同主播近7场平均24单；需结合开场录屏与同商品历史较好开场继续确认。',
    linked8:'8P6A本场仅挂链未讲解，曝光960、点击142、自然成交4件；当前只提示可增加讲解验证，不判断商品讲解异常。',
    ctr6:'6T2M曝光8,600，曝光点击率8.3%，低于前5次13.1%；点击成交率4.62%接近历史4.40%，重点回看穿搭、主图与场景表达。',
    new8:'8PBT为首次正式销售，本场两轮讲解成交5件；暂无同款历史数据，本场只建立首场记录。',
    opp8:'8DF0绿色曝光1,260，曝光点击率18.73%、点击成交率5.51%均高于近期表现；样本仍小，只能判断值得继续验证。',
    paid:'16:32–16:52投放消耗增加31%，付费成交金额下降18%；同期话术结构接近，语速与分贝升高，二者只作关联证据，不作为原因结论。',
    cvr89:'89ZP曝光点击率15.56%接近历史15.10%，点击成交率2.10%低于历史3.40%；价格一致，赠品条件不同。',
    refund7:'7K3Q本次退款率25%，高于前8次平均12%；当前仅能回看本次商品讲解相关原话，不能推断退款用户画像或其听过的内容。',
    linked9:'9R2Q本场仅挂链未讲解，曝光420、成交1件；没有讲解段且样本较少，只保留待观察记录。'
  },
  actions:{
    opening:'补足8NRQ开场场景表达并继续观察前15分钟。',linked8:'下一场为8P6A安排明确讲解段，验证挂链表现能否延续。',ctr6:'分别验证6T2M浅色穿搭、主图B与场景表达，避免同时改动多项。',new8:'继续积累8PBT后续场次数据。',opp8:'下一场适度增加8DF0绿色讲解与曝光，继续验证稳定性。',paid:'保持其他条件稳定，结合录屏验证讲解节奏。',cvr89:'继续验证89ZP赠品条件与促单话术。',refund7:'人工核对7K3Q尺码、版型与功能承诺原话。',linked9:'继续观察9R2Q挂链数据，样本充分前不做异常判断。'
  }
};
mainSession.hostReport='<h3>一、表现较好的部分</h3><p>8DF0绿色本次场景和利益点表达完整，可在增加验证量时保持。</p><h3>二、需要调整的部分</h3><p>6T2M补足穿搭场景展示；89ZP继续核对促单与权益表达；7K3Q回看尺码、版型和功能承诺原话。</p><h3>三、讲解状态</h3><p>16:34–16:41话术结构接近历史时段，但语速535字/分钟、分贝81dB，均高于同商品同主播近期水平。仅用于辅助回看，不直接解释成交变化。</p><h3>四、下场练习重点</h3><p>保持已验证表达顺序，分别完成开场场景、商品展示与合规权益说明。</p>';
mainSession.tasks=[{task:'准备6T2M浅色下装对比穿搭',owner:'运营 陈晨',deadline:'下场前'},{task:'下一场增加8DF0绿色验证量',owner:'',deadline:''},{task:'核对7K3Q尺码与功能承诺原话',owner:'主播 小福',deadline:''}];

function makeMinuteTimeline(start,end){const a=[],s=toMinutes(start),e=toMinutes(end);for(let n=s;n<=e;n++){a.push(`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`);}return a;}
function buildMetricSeries(session,quiet=false){
  const times=makeMinuteTimeline(session.info.start,session.info.end),at=(t)=>toMinutes(t)-toMinutes(session.info.start);
  const between=(i,a,b)=>i>=at(a)&&i<=at(b),round=(n,d=0)=>Number(n.toFixed(d));
  const values={gmv:[],spend:[],exposure:[],online:[],avgWatch:[],productCtr:[],productCvr:[],interaction:[],followRate:[],negativeRate:[],negativeCount:[],refundRate:[],orders:[]};
  times.forEach((_,i)=>{
    const wave=Math.sin(i/13)*520+Math.sin(i/5)*180,base=quiet?4300:4700;
    let gmv=Math.max(350,base+wave+(i%47===0?3600:0)),spend=quiet?48+Math.sin(i/20)*4:52+Math.sin(i/18)*7;
    if(!quiet&&between(i,'16:32','16:52')){const r=(i-at('16:32'))/20;gmv=4200-r*1500+Math.sin(i)*170;spend=58+r*28;}
    values.gmv.push(round(gmv));values.spend.push(round(spend,1));
    values.exposure.push(round((quiet?820:930)+Math.sin(i/9)*110+(i%31===0?260:0)));
    values.online.push(round((quiet?380:460)+Math.sin(i/17)*55));values.avgWatch.push(round(82+Math.sin(i/21)*9,1));
    let ctr=quiet?13.4+Math.sin(i/16):14.2+Math.sin(i/15)*1.4;if(!quiet&&between(i,'14:05','14:28'))ctr=8.3+Math.sin(i/3)*.35;if(!quiet&&between(i,'15:56','16:18'))ctr=18.7+Math.sin(i/4)*.4;
    let cvr=quiet?4.1+Math.sin(i/19)*.25:4.3+Math.sin(i/18)*.45;if(!quiet&&between(i,'15:56','16:18'))cvr=5.6+Math.sin(i/5)*.25;if(!quiet&&between(i,'17:04','17:40'))cvr=2.1+Math.sin(i/4)*.18;
    values.productCtr.push(round(ctr,2));values.productCvr.push(round(cvr,2));values.interaction.push(round(6.4+Math.sin(i/14)*.7,2));values.followRate.push(round(2.8+Math.sin(i/24)*.35,2));values.negativeRate.push(round(.18+Math.max(0,Math.sin(i/27))*.08,2));values.negativeCount.push(round(1+Math.max(0,Math.sin(i/11))*3));values.refundRate.push(round(!quiet&&between(i,'17:48','18:15')?25:11.8+Math.sin(i/29),2));values.orders.push(round(gmv/900));
  });
  const defs={gmv:['成交金额','元','currency'],spend:['投放消耗','元','currency'],exposure:['曝光人数','人','number'],online:['在线人数','人','number'],avgWatch:['人均观看时长','秒','number'],productCtr:['商品点击率','%','percent'],productCvr:['点击成交率','%','percent'],interaction:['互动率','%','percent'],followRate:['关注率','%','percent'],negativeRate:['负反馈率','%','percent'],negativeCount:['负反馈次数','次','number'],refundRate:['退款率','%','percent'],orders:['成交订单','单','number']};
  session.minuteTimeline=times;session.metricSeries=Object.fromEntries(Object.entries(defs).map(([key,[name,unit,axisFormat]])=>[key,{name,unit,axisFormat,values:values[key]}]));
}
buildMetricSeries(mainSession);
mainSession.sessionId='live-20260907-1300';mainSession.reviewStatus='pending';
mainSession.liveStatus='ended';
const completedSession=clone(mainSession);
completedSession.name='已完成复盘场';
completedSession.sessionId='live-20260910-1300';
completedSession.info={title:'秋冬日常直播',date:'2026-09-10',start:'13:00',end:'18:10',duration:'5小时10分',host:'小福',operator:'陈晨'};
completedSession.reviewStatus='completed';
completedSession.liveStatus='ended';
completedSession.reviewedItemIds=['opening','opp8','cvr89'];
completedSession.reviewItems=completedSession.reviewItems.filter(item=>completedSession.reviewedItemIds.includes(item.id)||item.id==='operation-switch');
completedSession.products={opp8:completedSession.products.opp8,cvr89:completedSession.products.cvr89};
completedSession.events=[{time:'15:56',label:'切换主推商品',detail:'8NRQ → 8DF0绿色'}];
completedSession.report={strategy:'本场以8NRQ开场，15:56切换主推8DF0绿色，后续复盘89ZP的点击成交承接。',bullets:{opening:'开场15分钟出单低于同主播近期平均，回看后确认场景表达较少。',opp8:'8DF0绿色在较低曝光下CTR和CVR均高于近期表现，本次只确认继续验证。',cvr89:'89ZP曝光点击正常，点击成交低于近期表现；价格一致，继续验证赠品条件和促单表达。'},actions:{opening:'保留8NRQ开场场景化表达。',opp8:'下场增加8DF0绿色讲解量继续验证。',cvr89:'保持价格不变，单独验证赠品条件与促单表达。'}};
completedSession.hostReport='<h3>一、表现较好的部分</h3><p>8DF0绿色的场景和利益点表达完整，复盘确认下场保留。</p><h3>二、需要调整的部分</h3><p>8NRQ开场补足使用场景；89ZP增加清晰的利益点和促单表达。</p><h3>三、讲解状态</h3><p>本次没有将主播状态作为独立结论。</p><h3>四、下场练习重点</h3><p>按“场景—利益点—促单”顺序完成一轮89ZP讲解。</p>';
completedSession.tasks=[{task:'下场增加8DF0绿色验证量',owner:'运营 陈晨',deadline:'下场前'},{task:'验证89ZP促单表达',owner:'主播 小福',deadline:''}];
completedSession.reviewConclusions={opening:'运营与主播确认：开场时场景表达较少，下场保留数据口径不变，先验证表达调整。',opp8:'运营与主播确认：8DF0绿色当前只能判断值得继续验证，不作爆款结论。',cvr89:'运营与主播确认：价格与历史表现较好场次一致，下场继续验证赠品条件和促单表达。'};
completedSession.formalReview={savedAt:'2026-09-10 23:48',duration:'28:16',operatorHtml:'<h3>一、本场策略与整体表现</h3><p>本场以8NRQ开场，15:56切换主推8DF0绿色，后续重点复盘89ZP成交承接。</p><h3>二、关键数据、机会及当场动作</h3><ul><li>开场15分钟出单偏慢，回看确认场景表达较少。</li><li>8DF0绿色在较低曝光下转化高于近期，当前仅作继续验证的机会。</li><li>89ZP价格一致，点击成交偏低，本场未发生临时改价或换赠品。</li></ul><h3>三、下场动作</h3><ul><li>增加8DF0绿色讲解量。</li><li>验证89ZP赠品条件和促单表达。</li></ul>',hostHtml:completedSession.hostReport,tasks:completedSession.tasks};
buildMetricSeries(completedSession,true);
completedSession.minuteTimeline.forEach((time,index)=>{const minute=toMinutes(time);if(minute<=toMinutes('13:15')){completedSession.metricSeries.gmv.values[index]=2600+index*45;completedSession.metricSeries.orders.values[index]=3;}if(minute>=toMinutes('15:56')&&minute<=toMinutes('16:18')){completedSession.metricSeries.productCtr.values[index]=18.7;completedSession.metricSeries.productCvr.values[index]=5.6;}if(minute>=toMinutes('17:04')&&minute<=toMinutes('17:40'))completedSession.metricSeries.productCvr.values[index]=2.1;});
demoSessions.completed=completedSession;
delete demoSessions.productCtr;delete demoSessions.hostState;delete demoSessions.refund;delete demoSessions.opportunity;delete demoSessions.newProduct;

const timelineDefaults = {
  opening:{lane:'traffic_paid',shortTitle:'开场起量慢'},
  paid:{lane:'traffic_paid',shortTitle:'消耗成交背离'},
  product_ctr:{lane:'product',shortTitle:'CTR偏低'},
  product_cvr:{lane:'product',shortTitle:'CVR偏低'},
  refund:{lane:'product',shortTitle:'退款率偏高'},
  opportunity_product:{lane:'product',shortTitle:'8DF0机会款'},
  new_product:{lane:'product',shortTitle:'新品待观察'},
  linked_product_opportunity:{lane:'product',shortTitle:'8P6A挂链机会'},
  linked_product_observation:{lane:'product',shortTitle:'9R2Q挂链待观察'}
};
function splitRange(range){const parts=range.split('–');return [parts[0],parts[1]||parts[0]];}
Object.values(demoSessions).forEach(session=>{
  session.reviewItems.forEach(item=>{
    const [startTime,endTime]=splitRange(item.timeRange);
    Object.assign(item,timelineDefaults[item.category]||{}, {startTime:item.startTime||startTime,endTime:item.endTime||endTime,detailType:item.detailType||item.detailView,relatedItemIds:item.relatedItemIds||[],relatedMetrics:item.relatedMetrics||[]});
  });
});
Object.values(demoSessions).forEach(session=>session.reviewItems.forEach(item=>{
  item.relatedItemIds.forEach(id=>{const other=session.reviewItems.find(candidate=>candidate.id===id);if(other&&!other.relatedItemIds.includes(item.id))other.relatedItemIds.push(item.id);});
}));
function validateProductReviewItems(session){
  const productCategories=new Set(['product_ctr','product_cvr','refund','opportunity_product','new_product','linked_product_opportunity','linked_product_observation']);
  session.reviewItems.filter(item=>productCategories.has(item.category)).forEach(item=>{
    if(typeof item.isExplained!=='boolean')throw new Error(`${item.id} 缺少讲解段状态`);
    if(item.type==='anomaly'&&!item.isExplained)throw new Error(`${item.id}：挂链未讲解商品不能生成商品异常`);
    if(!item.isExplained&&!['linked_only_opportunity','linked_only_observation'].includes(item.displayMode))throw new Error(`${item.id}：挂链未讲解商品 displayMode 非法`);
    if(item.isExplained&&item.displayMode!=='explained_product')throw new Error(`${item.id}：讲解商品必须使用 explained_product`);
  });
}
Object.values(demoSessions).forEach(validateProductReviewItems);
if (typeof window !== 'undefined') window.demoSessions = demoSessions;

const sessionsByDate=Object.entries(demoSessions).reduce((map,[key,session])=>{(map[session.info.date]||(map[session.info.date]=[])).push({key,sessionId:session.sessionId,name:session.info.title,startTime:session.info.start,endTime:session.info.end,reviewStatus:session.reviewStatus});return map;},{});

const storedSessionKey=localStorage.getItem(SESSION_KEY);
const modeParam=new URLSearchParams(location.search).get('mode');
let currentKey = (location.pathname.endsWith('review.html')||modeParam==='review')&&storedSessionKey?storedSessionKey:'comprehensive';
if (!demoSessions[currentKey]) currentKey = 'comprehensive';
let endedStage = 'home', activeItemId = null, recordingTimer = null, recordingSeconds = 0;
const sessionStages = {};
let cockpitMode = new URLSearchParams(location.search).get('mode')==='review'?'review':'live';
let timelineFilter = 'all',statusFilter='all',selectedMetrics=['gmv','spend'],cursorLocked=false,cursorIndex=null;
let selectedDate=demoSessions[currentKey].info.date,calendarOpen=false,calendarYear=Number(selectedDate.slice(0,4)),calendarMonth=Number(selectedDate.slice(5,7))-1;
const viewed = {};

function pct(n){ return `${Number(n).toFixed(Number(n)%1?2:0)}%`; }
function toast(text){ const r=$('.qj-toast-region'); if(!r)return; r.innerHTML=`<div class="qj-toast is-success" role="status"><span class="qj-toast__icon">✓</span><span>${text}</span></div>`; clearTimeout(window.toastT); window.toastT=setTimeout(()=>r.innerHTML='',2400); }
function sessionOptions(date=selectedDate){return (sessionsByDate[date]||[]).map(x=>{const state=sessionLifecycle(demoSessions[x.key],x.key),label=state==='completed'?'已复盘':state==='reviewing'?'复盘中':state==='draft_ready'?'正文待保存':'待复盘';return `<option value="${x.key}" ${x.key===currentKey?'selected':''}>${x.name} ${x.startTime}–${x.endTime} · ${label}</option>`;}).join('')||'<option value="">当天暂无已结束直播场次</option>';}
function demoPicker(){return `<label class="qj-demo-picker"><span><strong>历史场次</strong><small>${currentShop.name}</small></span><select class="qj-select" data-session-select>${Object.entries(demoSessions).map(([key,s])=>`<option value="${key}" ${key===currentKey?'selected':''}>${s.info.date} · ${s.info.title}</option>`).join('')}</select></label>`;}
function switchSession(key){if(!key||!demoSessions[key])return;if(recordingTimer){toast('请先结束当前复盘录音');renderCockpitReview();return;}sessionStages[currentKey]=endedStage;currentKey=key;selectedDate=demoSessions[key].info.date;calendarYear=Number(selectedDate.slice(0,4));calendarMonth=Number(selectedDate.slice(5,7))-1;calendarOpen=false;localStorage.setItem(SESSION_KEY,key);endedStage=sessionStages[key]||'home';timelineFilter='all';statusFilter='all';selectedMetrics=['gmv','spend'];cursorLocked=false;cursorIndex=null;activeItemId=null;renderCockpitReview();if($('[data-formal-review-page]'))renderReview();}
function dateKey(year,month,day){return `${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;}
function calendarPanel(){const first=new Date(calendarYear,calendarMonth,1),days=new Date(calendarYear,calendarMonth+1,0).getDate(),leading=(first.getDay()+6)%7,cells=[];for(let i=0;i<42;i++){const day=i-leading+1,date=new Date(calendarYear,calendarMonth,day),inMonth=day>=1&&day<=days,key=dateKey(date.getFullYear(),date.getMonth(),date.getDate()),sessions=sessionsByDate[key]||[],states=sessions.map(x=>sessionLifecycle(demoSessions[x.key],x.key)),hasLive=sessions.length>0,pendingCount=states.filter(x=>x!=='completed').length,completedCount=states.filter(x=>x==='completed').length,allCompleted=hasLive&&pendingCount===0,future=date>new Date('2026-09-11T23:59:59'),statusText=!hasLive?'':allCompleted?`${sessions.length}场直播 · 已复盘`:`${sessions.length}场直播 · ${pendingCount}场待复盘${completedCount?` · ${completedCount}场已复盘`:''}`;cells.push(`<button class="qj-date-picker__cell ${key===selectedDate?'is-selected':''} ${hasLive?'has-live':''} ${allCompleted?'is-reviewed':'has-pending'}" data-calendar-date="${key}" ${!inMonth||future||!hasLive?'disabled':''} aria-label="${key}${statusText?`，${statusText}`:''}" title="${statusText}"><span>${date.getDate()}</span>${allCompleted?'<i>✓</i>':hasLive?'<i>•</i>':''}</button>`);}return `<div class="qj-date-picker__panel session-calendar" role="dialog" aria-label="选择直播日期"><div class="session-calendar__header"><button class="qj-button qj-button--icon qj-button--text" data-calendar-nav="-1" aria-label="上一月">‹</button><strong>${calendarYear}年 ${calendarMonth+1}月</strong><button class="qj-button qj-button--icon qj-button--text" data-calendar-nav="1" aria-label="下一月">›</button></div><div class="session-calendar__week"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div><div class="qj-date-picker__grid">${cells.join('')}</div><div class="qj-date-picker__footer"><span class="is-pending">• 待复盘</span><span class="is-completed">✓ 已复盘</span></div></div>`;}
function bindSessionSelect(root=document){$$('[data-session-select]',root).forEach(s=>s.addEventListener('change',e=>switchSession(e.target.value)));$('[data-date-trigger]',root)?.addEventListener('click',()=>{calendarOpen=!calendarOpen;renderCockpitReview();});$$('[data-calendar-nav]',root).forEach(button=>button.addEventListener('click',()=>{calendarMonth+=Number(button.dataset.calendarNav);if(calendarMonth<0){calendarMonth=11;calendarYear--;}if(calendarMonth>11){calendarMonth=0;calendarYear++;}calendarOpen=true;renderCockpitReview();}));$$('[data-calendar-date]',root).forEach(button=>button.addEventListener('click',()=>{const entries=sessionsByDate[button.dataset.calendarDate]||[];if(entries.length)switchSession(entries[0].key);}));}

const laneMeta={traffic_paid:{label:'流量 / 投放'},product:{label:'商品'},talk_state:{label:'话术 / 状态'},operation:{label:'运营事件'}};
const filterMeta=[['all','全部'],['traffic_paid','流量/投放'],['product','商品'],['talk_state','话术/状态']];
const statusMeta=[['all','全部状态'],['anomaly','异常'],['opportunity','机会'],['observation','待观察']];
function toMinutes(value){const [h,m]=value.split(':').map(Number);return h*60+m;}
function timeLabel(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function timelinePosition(value,session){const start=toMinutes(session.info.start),end=toMinutes(session.info.end);return Math.max(0,Math.min(100,(toMinutes(value)-start)/(end-start)*100));}
function timelineTicks(session){const start=toMinutes(session.info.start),end=toMinutes(session.info.end),ticks=[start];for(let n=(Math.floor(start/60)+1)*60;n<end;n+=60)ticks.push(n);if(ticks.at(-1)!==end)ticks.push(end);return ticks.map(n=>({label:timeLabel(n),left:(n-start)/(end-start)*100}));}
function itemTypeLabel(type){return type==='opportunity'?'机会':type==='observation'?'待观察':type==='event'?'事件':'异常';}
function businessItems(session){return session.reviewItems.filter(item=>item.type!=='event');}
function filteredBusinessItems(session){return businessItems(session).filter(item=>(timelineFilter==='all'||item.lane===timelineFilter)&&(statusFilter==='all'||item.type===statusFilter));}
function defaultTimelineItem(session){return [...filteredBusinessItems(session)].sort((a,b)=>toMinutes(a.startTime)-toMinutes(b.startTime))[0]||[...businessItems(session)].sort((a,b)=>toMinutes(a.startTime)-toMinutes(b.startTime))[0];}
function countByLane(session,lane){return businessItems(session).filter(item=>item.lane===lane).length;}
function reviewCounts(session){return ['anomaly','opportunity','observation'].map(type=>({type,count:businessItems(session).filter(item=>item.type===type).length})).filter(x=>x.count);}
function isRelated(item,selected){if(!selected)return false;const overlap=toMinutes(item.startTime)<=toMinutes(selected.endTime)&&toMinutes(item.endTime)>=toMinutes(selected.startTime);return item.id===selected.id||item.relatedItemIds.includes(selected.id)||selected.relatedItemIds.includes(item.id)||overlap;}
function selectedBusiness(session){const item=session.reviewItems.find(candidate=>candidate.id===activeItemId)||defaultTimelineItem(session);if(!item)return null;return item.type==='event'?(session.reviewItems.find(candidate=>item.relatedItemIds.includes(candidate.id)&&candidate.type!=='event')||item):item;}
function compactMetric(value,format){if(format==='percent')return `${Number(value).toFixed(1)}%`;if(format==='currency'&&value>=10000)return `${(value/10000).toFixed(value%10000?1:0)}W`;if(value>=1000)return `${(value/1000).toFixed(value%1000?1:0)}K`;return String(Math.round(value*10)/10);}
function fullMetric(value,series){return `${series.axisFormat==='currency'?'¥':''}${Number(value).toLocaleString('zh-CN',{maximumFractionDigits:series.axisFormat==='percent'?2:1})}${series.axisFormat==='percent'?'%':series.axisFormat==='currency'?'':series.unit}`;}
function niceMax(values){const max=Math.max(...values,1),power=10**Math.floor(Math.log10(max)),scaled=max/power,step=scaled<=2?2:scaled<=5?5:10;return step*power;}
function seriesPath(values,max){return values.map((value,index)=>`${index?'L':'M'}${(index/(values.length-1)*1000).toFixed(2)} ${(210-value/max*174).toFixed(2)}`).join(' ');}
function metricSelector(session){return `<div class="metric-selector" aria-label="曲线指标选择">${Object.entries(session.metricSeries).map(([key,series])=>`<button class="metric-chip ${selectedMetrics.includes(key)?'is-selected':''}" data-metric-key="${key}" aria-pressed="${selectedMetrics.includes(key)}"><i></i>${series.name}</button>`).join('')}<span class="qj-card__meta">最多同时查看2项</span></div>`;}
function timelineChart(session,selected){
  const ticks=timelineTicks(session),series=selectedMetrics.map(key=>[key,session.metricSeries[key]]).filter(([,value])=>value),maxes=series.map(([,value])=>niceMax(value.values));
  const selectedStart=selected?timelinePosition(selected.startTime,session):0,selectedEnd=selected?timelinePosition(selected.endTime,session):0;
  let grid='',axis='';for(let index=0;index<=5;index++){const y=36+index*34.8;grid+=`<line x1="0" y1="${y}" x2="1000" y2="${y}"/>`;const leftValue=maxes[0]*(5-index)/5;axis+=`<text x="8" y="${y-5}" text-anchor="start">${compactMetric(leftValue,series[0]?.[1].axisFormat)}</text>`;if(series[1]){const rightValue=maxes[1]*(5-index)/5;axis+=`<text x="992" y="${y-5}" text-anchor="end">${compactMetric(rightValue,series[1][1].axisFormat)}</text>`;}}
  return `<div class="timeline-chart-grid"><div class="timeline-chart-side"><strong>${series[0]?.[1].name||''}</strong></div><div class="timeline-chart-wrap" data-chart-plot><div class="timeline-axis-names"><span>${series[0]?.[1].name||''}</span><span>${series[1]?.[1].name||''}</span></div><svg class="timeline-overview-chart" viewBox="0 0 1000 230" preserveAspectRatio="none" role="img" aria-label="整场分钟指标趋势"><g class="overview-grid">${grid}</g>${selected&&selectedStart!==selectedEnd?`<rect class="overview-selected-range" x="${selectedStart*10}" y="36" width="${Math.max(4,(selectedEnd-selectedStart)*10)}" height="174"/>`:''}${series.map(([key,value],index)=>`<path class="overview-series series-${index}" data-series-key="${key}" d="${seriesPath(value.values,maxes[index])}"/>`).join('')}<g class="overview-axis">${axis}</g><rect class="overview-hit" width="1000" height="230" data-chart-hit/></svg></div></div><div class="timeline-axis"><span></span><div>${ticks.map(t=>`<time style="--left:${t.left}%">${t.label}</time>`).join('')}</div></div>`;
}
function itemPreviewType(item){if(item.type==='event')return '实际记录事件 / 同期证据';if(item.lane==='product')return item.type==='anomaly'?'商品异常':item.type==='opportunity'?'商品机会':'商品待观察';return `${laneMeta[item.lane]?.label||''}${item.type==='opportunity'?'机会':item.type==='observation'?'待观察':'异常'}`;}
function sessionFormalRecord(session,key=currentKey){const stored=JSON.parse(localStorage.getItem(FORMAL_KEY)||'{}')[key];return stored||session.formalReview||null;}
function sessionIsCompleted(session,key=currentKey){return Boolean(sessionFormalRecord(session,key))||session.reviewStatus==='completed';}
function sessionLifecycle(session,key=currentKey){if(session.liveStatus==='live')return 'live';if(sessionIsCompleted(session,key))return 'completed';if(key===currentKey&&recordingTimer)return 'reviewing';if(sessionStages[key]==='draft_ready'||(key===currentKey&&endedStage==='draft_ready'))return 'draft_ready';return 'pending';}
function sessionStateLabel(state){return state==='live'?'直播中':state==='completed'?'已复盘':state==='reviewing'?'正在复盘':state==='draft_ready'?'录音已完成 · 正文待保存':'待复盘';}
function reviewedItemIds(session,key=currentKey){return sessionFormalRecord(session,key)?.reviewedItemIds||session.reviewedItemIds||[];}
function hoverDetail(item,session){const explained=typeof item.isExplained==='boolean'?`<span class="timeline-hover__row"><em>讲解状态</em><b>${item.isExplained?'已讲解':'挂链未讲解'}</b></span>`:'',reviewed=sessionIsCompleted(session)&&reviewedItemIds(session).includes(item.id)?'<span class="timeline-hover__row"><em>复盘状态</em><b>已在本次复盘中讨论</b></span>':'';return `<span class="timeline-hover" role="tooltip"><time>${item.timeRange}</time><strong>${item.title}</strong><span class="timeline-hover__data">${item.current?`<span>${item.current}</span>`:''}${item.compare?`<span>${item.compare}</span>`:''}${item.difference?`<b>${item.difference}</b>`:''}</span>${explained}${reviewed}<span class="timeline-hover__row"><em>类型</em><b>${itemPreviewType(item)}</b></span></span>`;}
function layoutLaneItems(items,session){const levels=[-Infinity,-Infinity],shown=[],overflow=[];[...items].sort((a,b)=>toMinutes(a.startTime)-toMinutes(b.startTime)).forEach(item=>{const left=timelinePosition(item.startTime,session),right=Math.max(left+7,timelinePosition(item.endTime,session));const level=levels.findIndex(end=>left>end+1);if(level<0)overflow.push(item);else{levels[level]=right;shown.push({item,level});}});return {shown,overflow};}
function timelineItem(item,session,selected,level=0){const left=timelinePosition(item.startTime,session),end=timelinePosition(item.endTime,session),point=item.startTime===item.endTime,width=point?0:Math.max(2,end-left),related=isRelated(item,selected),muted=selected&&!related;return `<button class="timeline-item type-${item.type} ${item.id===selected?.id?'is-selected':''} ${related&&item.id!==selected?.id?'is-related':''} ${muted?'is-muted':''} ${left>74?'hover-align-right':''}" style="--left:${left}%;--width:${width}%;--level:${level}" data-timeline-item="${item.id}"><span class="timeline-item__mark">${item.type==='opportunity'?'★':item.type==='event'?'◆':'●'}</span><span class="timeline-item__label">${item.shortTitle||item.title}</span>${hoverDetail(item,session)}</button>`;}
function visibleLaneKeys(){return timelineFilter==='all'?Object.keys(laneMeta):[timelineFilter,'operation'].filter((value,index,array)=>array.indexOf(value)===index);}
function renderLane(session,lane,selected,ticks){
  let items=session.reviewItems.filter(item=>item.lane===lane);
  if(statusFilter!=='all'&&lane!=='operation')items=items.filter(item=>item.type==='event'||item.type===statusFilter);
  const layout=layoutLaneItems(items,session),overflowAt=layout.overflow[0]?timelinePosition(layout.overflow[0].startTime,session):0;
  return `<div class="timeline-lane ${selected&&items.some(item=>isRelated(item,selected))?'has-related':''}"><div class="timeline-lane__label">${laneMeta[lane].label}<small>${countByLane(session,lane)||''}</small></div><div class="timeline-lane__track">${ticks.map(t=>`<i style="--left:${t.left}%"></i>`).join('')}${layout.shown.map(({item,level})=>timelineItem(item,session,selected,level)).join('')}${layout.overflow.length?`<button class="timeline-overflow" style="--left:${overflowAt}%">+${layout.overflow.length}<span class="timeline-hover"><strong>该时间附近共${layout.overflow.length}项</strong>${layout.overflow.map(item=>`<span>${item.timeRange} · ${item.title}</span>`).join('')}</span></button>`:''}${!items.length?'<span class="timeline-empty">本场无记录</span>':''}</div></div>`;
}
function renderTimeline(session){
  const selected=selectedBusiness(session);if(!activeItemId&&selected)activeItemId=selected.id;const ticks=timelineTicks(session);
  return `<section class="qj-card timeline-shell" aria-label="整场直播数据与复盘时间轴"><div class="qj-card__header"><div><h2 class="qj-card__title">整场数据与事件</h2><div class="qj-card__meta">分钟数据与复盘项共用同一时间轴；点击曲线可锁定某一分钟</div></div><div class="timeline-legend"><span class="type-anomaly">● 异常</span><span class="type-opportunity">★ 机会</span><span class="type-observation">● 待观察</span><span class="type-event">◆ 事件/证据</span></div></div><div class="qj-card__body">${metricSelector(session)}<div class="timeline-stage" data-time-stage>${timelineChart(session,selected)}${visibleLaneKeys().map(lane=>renderLane(session,lane,selected,ticks)).join('')}<div class="time-cursor" data-time-cursor hidden><span></span><div class="time-cursor__tooltip" data-cursor-tooltip></div></div></div></div></section>`;
}
function renderSessionSelector(session){const state=sessionLifecycle(session),complete=state==='completed',stateClass=complete?'is-success':state==='reviewing'?'is-error':'is-warning';return `<section class="qj-card session-selector"><div class="qj-card__body"><div class="qj-field qj-date-picker"><span class="qj-field__label">直播日期</span><button class="qj-date-picker__input" data-date-trigger aria-expanded="${calendarOpen}"><span>▣</span><strong>${selectedDate}</strong><span>▾</span></button>${calendarOpen?calendarPanel():''}</div><label class="qj-field"><span class="qj-field__label">场次</span><select class="qj-select" data-session-select>${sessionOptions()}</select></label><div class="session-context"><span>${currentShop.name}</span><small>店铺由当前驾驶舱上下文确定</small><button class="qj-button qj-button--text qj-button--sm" data-reset-demo>重置演示数据</button></div><div class="session-selector__facts"><span>主播<strong>${session.info.host}</strong></span><span>运营<strong>${session.info.operator}</strong></span><span>直播时间<strong>${session.info.start}–${session.info.end}</strong></span><span>直播时长<strong>${session.info.duration}</strong></span><span>复盘状态<strong class="${stateClass}">${sessionStateLabel(state)}</strong></span></div></div></section>`;}
function renderReviewHeader(session){const counts=reviewCounts(session),formal=sessionFormalRecord(session),state=sessionLifecycle(session);let actions;if(state==='completed')actions=`<div class="completed-review-actions"><div><span class="qj-status is-success"><span class="qj-status__icon">✓</span><span class="qj-status__label">复盘已完成</span></span><small>正文保存于 ${formal.savedAt}</small></div><button class="qj-button qj-button--outline" data-view-review-recording>查看复盘录音</button><button class="qj-button qj-button--outline" data-view-formal="operator">查看运营复盘正文</button><button class="qj-button qj-button--outline" data-view-formal="host">查看主播复盘报告</button><a class="qj-button qj-button--primary" href="review.html">查看/编辑运营复盘正文</a></div>`;else if(state==='reviewing')actions='<div class="reviewing-header-state"><span class="qj-status is-error"><span class="qj-status__dot"></span><span class="qj-status__label">正在复盘</span></span><small>录音控件已固定在右下角</small></div>';else actions='<button class="qj-button qj-button--primary" data-start-recording>● 开始复盘录音</button>';return `<header class="qj-page__header review-overview"><div><h1 class="qj-page__title">本场值得复盘</h1><div class="qj-page__meta">先看整场数据如何变化，再沿时间回看异常、机会、待观察和实际事件</div><div class="review-counts">${counts.map(x=>`<button class="qj-tag qj-tag--${x.type==='anomaly'?'warning':x.type==='opportunity'?'success':'neutral'} ${statusFilter===x.type?'is-active':''}" data-status-filter="${x.type}">${itemTypeLabel(x.type)} ${x.count}项</button>`).join('')}</div></div>${actions}</header><div class="timeline-filter-row"><div><span class="filter-label">业务筛选</span><div class="qj-filter timeline-filters">${filterMeta.map(([key,label])=>`<button class="qj-filter__chip ${timelineFilter===key?'is-selected':''}" data-timeline-filter="${key}" aria-pressed="${timelineFilter===key}">${label}</button>`).join('')}</div></div><div><span class="filter-label">状态</span><div class="qj-filter timeline-filters">${statusMeta.map(([key,label])=>`<button class="qj-filter__chip ${statusFilter===key?'is-selected':''}" data-status-filter="${key}" aria-pressed="${statusFilter===key}">${label}</button>`).join('')}</div></div></div>`;}
function stripDetailHeader(html){return html.replace(/^<header class="qj-page__header">[\s\S]*?<\/header>/,'');}
function sameMetrics(a,b){return a.length===b.length&&a.every(key=>b.includes(key));}
function renderTimelineDetail(session){const item=session.reviewItems.find(i=>i.id===activeItemId)||defaultTimelineItem(session);if(!item)return '<section class="qj-state qj-state--empty"><div class="qj-state__title">本场没有达到规则阈值的复盘项</div><div class="qj-state__description">系统不会为了填满页面强行生成异常或机会。</div></section>';const fallback=item.type==='event'?session.reviewItems.find(i=>item.relatedItemIds.includes(i.id)&&i.type!=='event'):null,target=item.detailTargetId?session.reviewItems.find(i=>i.id===item.detailTargetId):fallback||item;if(recordingTimer)(viewed[currentKey]||(viewed[currentKey]=new Set())).add(target.id);const badge=itemTypeLabel(target.type),related=target.relatedMetrics||[],shown=sameMetrics(selectedMetrics,related),explainStatus=typeof target.isExplained==='boolean'?`<span class="qj-tag qj-tag--info">讲解状态：${target.isExplained?'已讲解':'挂链未讲解'}</span>`:'',conclusion=session.reviewConclusions?.[target.id]?`<section class="qj-alert is-success saved-conclusion"><span class="qj-alert__icon">✓</span><div class="qj-alert__content"><div class="qj-alert__title">本次复盘结论</div><div class="qj-alert__description">${session.reviewConclusions[target.id]}</div></div></section>`:'';let body;if(target.category==='opening')body=renderOpening(session);else if(target.category==='paid')body=renderPaid(session);else if(target.isExplained===false)body=renderLinkedProduct(session,target);else body=renderProduct(session,target);return `<section class="detail-heading"><div><div class="qj-cluster"><span class="qj-tag qj-tag--${target.type==='anomaly'?'warning':target.type==='opportunity'?'success':'neutral'}">${badge}</span>${explainStatus}<time>${target.timeRange}</time></div><h2>${target.title}</h2><p>${target.current}${target.compare?` · ${target.compare}`:''}${target.difference?` · ${target.difference}`:''}</p></div><div class="related-metrics"><span>关联指标：${related.map(key=>session.metricSeries[key]?.name).filter(Boolean).join('、')||'无'}</span>${related.length?shown?'<small>当前已展示关联指标</small>':'<button class="qj-button qj-button--outline" data-show-related>查看关联指标</button>':''}<small>同期关联只表示时间重合，不代表因果</small></div></section>${conclusion}<div class="timeline-detail">${stripDetailHeader(body)}</div>`;}
function renderReviewWorkbench(session){return `${renderSessionSelector(session)}${renderReviewHeader(session)}${renderTimeline(session)}${renderTimelineDetail(session)}`;}
function renderCockpitReview(){const root=$('[data-cockpit-review]');if(!root)return;const session=demoSessions[currentKey];root.innerHTML=endedStage==='draft_ready'&&!sessionIsCompleted(session)?renderSessionSelector(session)+renderCompletion(session):renderReviewWorkbench(session);bindSessionSelect(root);bindEnded(root,session);}
function setCockpitMode(mode){cockpitMode=mode;const url=new URL(location.href);if(mode==='review')url.searchParams.set('mode','review');else url.searchParams.delete('mode');history.replaceState(null,'',url);$$('[data-cockpit-mode]').forEach(b=>{const active=b.dataset.cockpitMode===mode;b.setAttribute('aria-selected',String(active));b.classList.toggle('is-active',active);});$('[data-cockpit-live]').hidden=mode!=='live';$('[data-cockpit-review]').hidden=mode!=='review';if(mode==='review')renderCockpitReview();}

function topbar(s){return `<header class="qj-topbar qj-demo-topbar"><div class="qj-status"><span class="qj-status__dot"></span><span class="qj-status__label">直播已结束</span></div><div class="qj-topbar__context"><strong>COS官方旗舰店 · ${s.info.title}</strong><div class="qj-page__meta">${s.info.date} · ${s.info.start}–${s.info.end}</div></div><div class="qj-topbar__profile">时长<strong>${s.info.duration}</strong></div><div class="qj-topbar__profile">主播<strong>${s.info.host}</strong></div><div class="qj-topbar__profile">运营<strong>${s.info.operator}</strong></div>${demoPicker()}<div class="qj-topbar__actions"><a class="qj-button qj-button--outline" href="live.html">查看直播看板</a><button class="qj-button qj-button--primary" data-start-recording ${recordingTimer?'disabled':''}>${recordingTimer?'复盘录音中':'● 开始复盘录音'}</button></div></header>`;}

function itemCard(i){const opp=i.type==='opportunity';return `<article class="qj-review-item ${opp?'is-opportunity':'is-anomaly'}"><span class="qj-tag ${opp?'qj-tag--success':'qj-tag--warning'}">${opp?'机会':'异常'}</span><div class="qj-review-item__main"><strong>${i.title}</strong><small>${i.timeRange}</small></div><div><b>${i.current}</b><small>本次</small></div><div><b>${i.compare}</b><small>比较对象</small></div><div class="${opp?'is-positive':'is-error'}"><b>${i.difference}</b><small>${opp?'判断':'差异'}</small></div><button class="qj-button ${opp?'qj-button--outline':'qj-button--primary'}" data-open-item="${i.id}">${i.button}</button></article>`;}
function renderHome(s){const a=s.reviewItems.filter(i=>i.type==='anomaly').length,o=s.reviewItems.filter(i=>i.type==='opportunity').length;return `<header class="qj-page__header"><div><h1 class="qj-page__title">本场值得复盘</h1><div class="qj-page__meta">点击复盘项查看对应录屏与数据</div></div><div class="qj-cluster"><span class="qj-tag qj-tag--warning">异常 ${a}项</span>${o?`<span class="qj-tag qj-tag--success">机会 ${o}项</span>`:''}</div></header><section class="qj-card"><div class="qj-card__body qj-review-list">${s.reviewItems.map(itemCard).join('')}</div></section>`;}

function video(title,time){return `<div class="qj-video"><span>▶</span><strong>${title}</strong><time>${time}</time></div>`;}
function metricGrid(d){return `<div class="qj-description qj-compact-metrics"><div class="qj-description__item"><div class="qj-description__label">成交订单</div><div class="qj-description__value">${d.orders}</div></div><div class="qj-description__item"><div class="qj-description__label">曝光</div><div class="qj-description__value">${d.exposure.toLocaleString()}</div></div><div class="qj-description__item"><div class="qj-description__label">曝光点击率</div><div class="qj-description__value">${pct(d.ctr)}</div></div><div class="qj-description__item"><div class="qj-description__label">点击成交率</div><div class="qj-description__value">${pct(d.cvr)}</div></div></div>`;}
function talkTable(talk, single=false, asrKey='base'){const compare=talk.compare||[];return `<section class="qj-card qj-section-gap" data-talk data-asr-key="${asrKey}"><div class="qj-card__header"><div><h2 class="qj-card__title">话术与ASR原话</h2><div class="qj-card__meta">每个ASR块仅一个主标签参与比例；副标签只用于检索</div></div>${!single&&Math.max(...talk.current.map((v,i)=>Math.abs(v-compare[i])))<=4?'<span class="qj-tag qj-tag--neutral">话术结构接近</span>':''}</div><div class="qj-card__body"><table data-kind="compare-table"><thead><tr><th>主标签</th><th>本次</th>${single?'':'<th>对比时段</th><th>差异</th>'}<th>原话</th></tr></thead><tbody>${labels.map((l,i)=>{const d=single?0:talk.current[i]-compare[i];return `<tr><td><strong>${l}</strong></td><td>${talk.current[i]}%</td>${single?'':`<td>${compare[i]}%</td><td class="${Math.abs(d)>=8?'is-error':''}">${d===0?'一致':`${d>0?'高':'低'}${Math.abs(d)}pp`}</td>`}<td><button class="qj-button qj-button--text" data-show-asr="${l}">查看原话（${baseAsr[l].length}条）</button></td></tr>`}).join('')}</tbody></table><div class="qj-talk-detail" data-talk-detail>选择标签查看多条ASR原文。录屏由运营自行结合上下文回看。</div></div></section>`;}
function hostStateBlock(h){if(!h)return'';return `<section class="qj-card qj-section-gap"><div class="qj-card__header"><div><h2 class="qj-card__title">话术结构接近，继续查看主播讲解状态</h2><div class="qj-card__meta">语速和分贝为确定性数据；情绪为辅助模型结果</div></div></div><div class="qj-card__body"><div class="qj-description"><div class="qj-description__item"><div class="qj-description__label">平均语速</div><div class="qj-description__value">${h.speed}字/分钟</div><div class="qj-card__meta">近5次${h.speedCompare} · 高${((h.speed/h.speedCompare-1)*100).toFixed(1)}%</div></div><div class="qj-description__item"><div class="qj-description__label">平均分贝</div><div class="qj-description__value">${h.db}dB</div><div class="qj-card__meta">近5次${h.dbCompare}dB · 高${h.db-h.dbCompare}dB</div></div></div><div class="qj-alert"><span class="qj-alert__icon">i</span><div><strong>辅助识别：${h.emotion}，置信度${h.confidence}%</strong><div class="qj-card__meta">仅用于辅助回看录屏，不作为原因结论。</div></div></div></div></section>`;}

function renderOpening(s){const d=s.opening;return `<header class="qj-page__header"><div class="qj-cluster"><button class="qj-button qj-button--outline" data-back>← 返回</button><div><h1 class="qj-page__title">开播15分钟同屏复盘</h1><div class="qj-page__meta">${d.product}</div></div></div></header><div class="qj-grid"><section class="qj-grid__item qj-card" data-span="12"><div class="qj-card__header"><h2 class="qj-card__title">当前开场</h2></div><div class="qj-card__body">${video('当前开场录屏',d.current.time)}${metricGrid(d.current)}</div></section><section class="qj-grid__item qj-card" data-span="12"><div class="qj-card__header"><h2 class="qj-card__title">${d.compare.label}</h2></div><div class="qj-card__body">${video('对比时段录屏',d.compare.time)}${metricGrid(d.compare)}</div></section></div>${talkTable(d.talk)}`;}
function renderPaid(s){const p=s.paid,spendDelta=Math.round((p.summary.anomalySpend/p.summary.beforeSpend-1)*100),gmvDelta=Math.round((p.summary.anomalyGmv/p.summary.beforeGmv-1)*100),duration=toMinutes(p.time.split('–')[1])-toMinutes(p.time.split('–')[0]);return `<header class="qj-page__header"><div class="qj-cluster"><button class="qj-button qj-button--outline" data-back>← 返回</button><div><h1 class="qj-page__title">付费消耗与成交分钟级复盘</h1><div class="qj-page__meta">异常时段 ${p.time}</div></div></div></header><section class="qj-card paid-evidence-summary"><div class="qj-card__header"><div><h2 class="qj-card__title">异常时段证据</h2><div class="qj-card__meta">趋势与区间高亮统一在上方整场曲线查看</div></div></div><div class="qj-card__body qj-description"><div class="qj-description__item"><div class="qj-description__label">投放消耗</div><div class="qj-description__value">+${spendDelta}%</div></div><div class="qj-description__item"><div class="qj-description__label">付费成交金额</div><div class="qj-description__value">${gmvDelta}%</div></div><div class="qj-description__item"><div class="qj-description__label">持续时间</div><div class="qj-description__value">${duration}分钟</div></div></div></section><section class="qj-card qj-section-gap"><div class="qj-card__body"><strong>${p.events.length?'已记录业务事件':'该异常时段无已记录的商品、价格或投放策略操作'}</strong>${p.events.map(e=>`<div>${e.time} ${e.label} · ${e.detail}</div>`).join('')}</div></section><div class="qj-grid qj-section-gap"><div class="qj-grid__item" data-span="8">${video('异常前稳定时段录屏','16:20–16:32')}</div><div class="qj-grid__item" data-span="8">${video('异常时段录屏',p.time)}</div><div class="qj-grid__item" data-span="8">${video('恢复时段录屏','16:52–17:04')}</div></div>${talkTable(p.talk)}${hostStateBlock(p.hostState)}`;}

function funnel(p){const focus=p.focus,rateKeys=[null,'ctr','cvr','refund'],nodes=[['曝光',p.exposure],['点击',p.clicks],['成交',p.orders],['退款',p.refunds]],focuses=focus==='opportunity'?[1,2]:[{ctr:1,cvr:2,refund:3,new:-1}[focus]];return `<div class="qj-funnel">${nodes.map((n,i)=>{const key=rateKeys[i],isFocus=focuses.includes(i),current=key?p.rates[key]:null,comparison=key&&p.compare?p.compare[key]:null,detail=key?`${key==='ctr'?'曝光点击率':key==='cvr'?'点击成交率':'退款率'}：本次 ${pct(current)}${comparison!==null?` · 对比 ${pct(comparison)}`:''}`:'';return `${i?'<span class="qj-funnel__arrow">→</span>':''}<div class="qj-funnel__node ${isFocus?'is-focus':'is-normal'}"><span>${n[0]}</span><strong>${n[1].toLocaleString()}</strong><small>${detail}</small>${isFocus?`<span class="qj-tag ${focus==='opportunity'?'qj-tag--success':'qj-tag--warning'}">${focus==='opportunity'?'值得继续验证':'需要复盘'}</span>`:comparison!==null&&i>0?'<span class="qj-tag qj-tag--neutral">正常</span>':''}</div>`}).join('')}</div>`;}
function factorTable(p){if(!p.factors?.length)return'';return `<section class="qj-card qj-section-gap"><div class="qj-card__header"><h2 class="qj-card__title">影响因素对比</h2><div class="qj-card__meta">差异是复盘线索，不直接作为原因</div></div><div class="qj-card__body"><table data-kind="factor-table"><thead><tr><th>因素</th><th>本次</th><th>历史较好场次</th><th>差异</th></tr></thead><tbody>${p.factors.map(r=>`<tr>${r.map((v,i)=>`<td>${i===3?`<span class="qj-tag ${v==='一致'?'qj-tag--neutral':'qj-tag--warning'}">${v}</span>`:v}</td>`).join('')}</tr>`).join('')}</tbody></table>${p.focus==='ctr'?'<div class="qj-image-compare"><div><span>当前主图 A</span><strong>深灰同色系画面</strong></div><div><span>历史主图 B</span><strong>米白下装形成层次</strong></div></div>':''}</div></section>`;}
function refundTalk(){return `<section class="qj-card qj-section-gap"><div class="qj-card__header"><div><h2 class="qj-card__title">本次商品讲解相关原话</h2><div class="qj-card__meta">不能说明退款用户实际听到这些内容</div></div></div><div class="qj-card__body"><div class="qj-alert is-warning"><span class="qj-alert__icon">!</span><div>当前拿不到退款用户画像，也没有退款用户—看播—话术链路。这里只供人工结合退款率和录屏复盘。</div></div><div class="qj-chip-row">${Object.entries(refundAsr).map(([k,v])=>`<button class="qj-button qj-button--outline" data-refund-asr="${k}">${k}相关原话（${v.length}条）</button>`).join('')}</div><div class="qj-talk-detail" data-refund-detail>选择一个主题查看多条ASR原文。</div></div></section>`;}
function opportunityExtra(s,p){return `<section class="qj-card qj-section-gap"><div class="qj-card__header"><div><h2 class="qj-card__title">为什么值得继续验证</h2><div class="qj-card__meta">整场趋势及事件时点统一在上方时间轴查看</div></div></div><div class="qj-card__body"><div class="qj-opportunity-grid"><div><span>曝光样本</span><strong>${p.exposure.toLocaleString()}</strong><small>绝对规模仍低</small></div><div><span>曝光点击率</span><strong>${pct(p.rates.ctr)}</strong><small>近期 ${pct(p.compare.ctr)} · 高${Math.round((p.rates.ctr/p.compare.ctr-1)*100)}%</small></div><div><span>点击成交率</span><strong>${pct(p.rates.cvr)}</strong><small>近期 ${pct(p.compare.cvr)} · 高${Math.round((p.rates.cvr/p.compare.cvr-1)*100)}%</small></div><div><span>${p.shortVideo.label}</span><strong>${p.shortVideo.exposure.toLocaleString()}</strong><small>仅作并列信号</small></div></div><div class="qj-alert is-success"><span class="qj-alert__icon">✓</span><div><strong>当前表现值得继续验证</strong><div class="qj-card__meta">不能写成“已经证明是爆款”。</div></div></div>${s.events.map(e=>`<div class="qj-event"><time>${e.time}</time><strong>${e.label}</strong><span>${e.detail}</span><small>事件只作证据，不代表因果</small></div>`).join('')}</div></section>`;}
function newExtra(p){return `<section class="qj-card qj-section-gap"><div class="qj-card__header"><div><h2 class="qj-card__title">当前可用参考</h2><div class="qj-card__meta">今年首次正式销售 · 去年无同款记录 · 不计算“低于历史”</div></div></div><div class="qj-card__body"><div class="qj-alert"><span class="qj-alert__icon">i</span><div><strong>本场${p.rounds}轮讲解，主要用于建立首场表现记录</strong><div class="qj-card__meta">样本较少，暂不判断是否异常。</div></div></div><div class="qj-opportunity-grid"><div><span>前置挂链曝光</span><strong>${p.prelaunch.exposure.toLocaleString()}</strong></div><div><span>前置挂链点击</span><strong>${p.prelaunch.clicks}</strong><small>${pct(p.prelaunch.ctr)}</small></div><div><span>前置挂链成交</span><strong>${p.prelaunch.orders}</strong><small>${pct(p.prelaunch.cvr)}</small></div><div><span>本场款色</span><strong>灰色 ${p.colors[0][1]}件</strong><small>其他颜色 ${p.colors[1][1]}件</small></div></div></div></section>`;}
function renderLinkedProduct(s,item){const p=s.products[item.id],opportunity=item.displayMode==='linked_only_opportunity',judgement=opportunity?'值得增加讲解验证':'当前样本较少，继续观察',suggestion=opportunity?'下场安排明确讲解段，再验证点击和成交表现是否延续。':'继续积累挂链数据；没有讲解段前不生成CTR、CVR或退款异常。';return `<header class="qj-page__header"><div><h1 class="qj-page__title">${p.product} · ${opportunity?'挂链机会':'挂链待观察'}</h1><div class="qj-page__meta">${p.time} · 挂链未讲解</div></div></header><section class="qj-card linked-product-detail"><div class="qj-card__header"><div><h2 class="qj-card__title">挂链基础表现</h2><div class="qj-card__meta">本时段不存在商品讲解段，不进入商品异常复盘</div></div><span class="qj-tag ${opportunity?'qj-tag--success':'qj-tag--neutral'}">讲解状态：挂链未讲解</span></div><div class="qj-card__body"><div class="qj-opportunity-grid"><div><span>曝光</span><strong>${p.exposure.toLocaleString()}</strong></div><div><span>点击</span><strong>${p.clicks.toLocaleString()}</strong><small>自然点击率 ${pct(p.rates.ctr)}</small></div><div><span>成交</span><strong>${p.orders}</strong><small>点击成交率 ${pct(p.rates.cvr)}</small></div><div><span>自然成交</span><strong>${p.naturalOrders}</strong></div></div>${p.shortVideo?`<div class="qj-description linked-evidence"><div class="qj-description__item"><div class="qj-description__label">${p.shortVideo.label}</div><div class="qj-description__value">${p.shortVideo.exposure.toLocaleString()}</div></div></div>`:''}<div class="qj-alert ${opportunity?'is-success':''}"><span class="qj-alert__icon">${opportunity?'✓':'i'}</span><div><strong>当前判断：${judgement}</strong><div class="qj-card__meta">${suggestion}</div></div></div></div></section>`;}
function renderProduct(s,item){const p=s.products[item.id];const title=p.focus==='opportunity'?`${p.product} · 机会复盘`:p.focus==='new'?`${p.product} · 首播记录`:`${p.product} · 商品复盘`,neutral=p.focus==='new';return `<header class="qj-page__header"><div class="qj-cluster"><button class="qj-button qj-button--outline" data-back>← 返回</button><div><h1 class="qj-page__title">${title}</h1><div class="qj-page__meta">${p.time}${p.compare?` · ${p.compare.label}`:' · 暂无同款历史数据'} · 讲解状态：已讲解</div></div></div></header><section class="qj-card"><div class="qj-card__header"><h2 class="qj-card__title">商品链路</h2><div class="qj-cluster"><span class="qj-tag qj-tag--info">讲解状态：已讲解</span><span class="qj-tag ${neutral?'qj-tag--neutral':p.focus==='opportunity'?'qj-tag--success':'qj-tag--warning'}">${itemTypeLabel(item.type)}</span></div></div><div class="qj-card__body">${funnel(p)}</div></section>${factorTable(p)}${p.focus==='refund'?refundTalk():''}${p.focus==='opportunity'?opportunityExtra(s,p):''}${p.focus==='new'?newExtra(p):''}<div class="qj-grid qj-section-gap"><div class="qj-grid__item" data-span="12">${video(`${p.product}本次录屏`,p.time)}</div>${p.compare?`<div class="qj-grid__item" data-span="12">${video('历史表现较好录屏','对比时段')}</div>`:''}</div>${p.focus==='refund'?talkTable(p.talk,true):talkTable(p.talk,!p.talk.compare)}${hostStateBlock(p.hostState)}`;}

function reportHtml(s,ids,useAll=false){const chosen=useAll?s.reviewItems.map(i=>i.id):ids;const bullets=chosen.map(id=>s.report.bullets[id]).filter(Boolean).map(x=>`<li>${x}</li>`).join('')||'<li>本次未打开具体复盘项，不补写结论。</li>';const acts=chosen.map(id=>s.report.actions[id]).filter(Boolean).map(x=>`<li>${x}</li>`).join('')||'<li>录音中未形成明确动作。</li>';return `<h3>一、本场策略与整体表现</h3><p>${s.report.strategy}</p><h3>二、关键数据、机会及当场动作</h3><ul>${bullets}</ul><h3>三、下场动作</h3><ul>${acts}</ul>`;}
function renderCompletion(s){const ids=[...(viewed[currentKey]||new Set())].filter(id=>s.report.bullets[id]);return `<section class="qj-card qj-complete"><div class="qj-card__body"><span class="qj-state__visual">✓</span><h1 class="qj-page__title">复盘录音已完成</h1><div class="qj-page__meta">录音 <span data-finished-duration>${formatTime(recordingSeconds)}</span> · ASR转写已完成 · 正式正文尚未保存</div><button class="qj-button qj-button--outline" data-show-transcript>查看录音转写</button></div></section><section class="qj-card qj-section-gap"><div class="qj-card__header"><div><h2 class="qj-card__title">运营复盘正文草稿</h2><div class="qj-card__meta">保存前是临时编辑状态；只引用本场配置与已查看证据</div></div><span data-save-state>待保存</span></div><div class="qj-card__body"><div class="qj-rich-text"><div contenteditable="true" data-draft>${reportHtml(s,ids)}</div></div></div><div class="qj-card__footer qj-split"><span class="qj-card__meta">只有点击保存后，场次才转为“已复盘”</span><div class="qj-page__actions"><button class="qj-button qj-button--primary" data-save-formal>保存复盘正文</button></div></div></section>`;}
function renderDetail(s){const item=s.reviewItems.find(i=>i.id===activeItemId);if(!item)return renderHome(s);if(item.category==='opening')return renderOpening(s);if(item.category==='paid')return renderPaid(s);if(item.isExplained===false)return renderLinkedProduct(s,item);return renderProduct(s,item);}
function renderEnded(){const root=$('[data-ended-app]');if(!root)return;const s=demoSessions[currentKey];root.innerHTML=topbar(s)+(endedStage==='home'?renderHome(s):endedStage==='detail'?renderDetail(s):renderCompletion(s));bindSessionSelect(root);bindEnded(root,s);}
function formatTime(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;}
function startRecording(){const session=demoSessions[currentKey];if(sessionLifecycle(session)==='completed'){toast('该场次已完成复盘');return;}endedStage='home';sessionStages[currentKey]='home';session.reviewStatus='reviewing';recordingSeconds=0;const a=$('[data-recorder]');a.hidden=false;$('[data-recording-time]').textContent='00:00';recordingTimer=setInterval(()=>{$('[data-recording-time]').textContent=formatTime(++recordingSeconds)},1000);renderCockpitReview();toast('复盘录音已开始，可继续切换时间轴复盘项');}
function stopRecording(){if(!recordingTimer)return;clearInterval(recordingTimer);recordingTimer=null;$('[data-recorder]').hidden=true;endedStage='draft_ready';sessionStages[currentKey]='draft_ready';demoSessions[currentKey].reviewStatus='draft_ready';renderCockpitReview();toast('录音已结束，已生成本场对应正文草稿');}
function resetDemoData(){if(recordingTimer){toast('请先结束当前复盘录音');return;}const formalMap=JSON.parse(localStorage.getItem(FORMAL_KEY)||'{}'),taskMap=JSON.parse(localStorage.getItem(TASK_KEY)||'{}');delete formalMap.comprehensive;delete taskMap.comprehensive;localStorage.setItem(FORMAL_KEY,JSON.stringify(formalMap));localStorage.setItem(TASK_KEY,JSON.stringify(taskMap));localStorage.setItem(SESSION_KEY,'comprehensive');delete viewed.comprehensive;delete sessionStages.comprehensive;demoSessions.comprehensive.reviewStatus='pending';currentKey='comprehensive';selectedDate=demoSessions.comprehensive.info.date;calendarYear=2026;calendarMonth=8;calendarOpen=false;endedStage='home';activeItemId=null;timelineFilter='all';statusFilter='all';selectedMetrics=['gmv','spend'];cursorLocked=false;cursorIndex=null;recordingSeconds=0;$('[data-recorder]').hidden=true;renderCockpitReview();toast('演示数据已重置，09-07已恢复为待复盘');}
function openModal(title,body,time=''){const m=$('#review-modal')||$('#evidence-modal');if(!m)return;$('[data-modal-title]',m).textContent=title;$('[data-modal-time]',m).textContent=time;const target=$('[data-modal-body]',m)||$('.qj-modal__body',m);target.innerHTML=body;m.hidden=false;m.setAttribute('aria-hidden','false');}
function closeModal(){const m=$('.qj-modal:not([hidden])');if(m){m.hidden=true;m.setAttribute('aria-hidden','true')}}
function renderAsrList(arr){return `<ol class="qj-asr-list">${arr.map((x,i)=>`<li ${i>=5?'hidden':''}>${x}</li>`).join('')}</ol>${arr.length>5?'<button class="qj-button qj-button--text" data-expand-asr>展开全部</button>':''}`;}
function bindTalk(root){$$('[data-talk]',root).forEach(box=>{$$('[data-show-asr]',box).forEach(b=>b.addEventListener('click',()=>{const arr=baseAsr[b.dataset.showAsr];const d=$('[data-talk-detail]',box);d.innerHTML=`<strong>${b.dataset.showAsr} · ASR原话</strong><div class="qj-card__meta">按原始讲解顺序，不由LLM改写，不提供逐句录屏定位</div>${renderAsrList(arr)}`;bindExpand(d);}));});$$('[data-refund-asr]',root).forEach(b=>b.addEventListener('click',()=>{const d=$('[data-refund-detail]',root);d.innerHTML=`<strong>${b.dataset.refundAsr}相关原话</strong><div class="qj-card__meta">仅属于本次商品讲解，不能证明退款用户听过</div>${renderAsrList(refundAsr[b.dataset.refundAsr])}`;bindExpand(d);}));}
function bindExpand(root){$('[data-expand-asr]',root)?.addEventListener('click',e=>{const hidden=$$('li[hidden]',root).length>0;$$('li',root).forEach((li,i)=>li.hidden=hidden?false:i>=5);e.currentTarget.textContent=hidden?'收起':'展开全部';});}
function cursorContent(session,index){const time=session.minuteTimeline[index],minute=toMinutes(time),metrics=selectedMetrics.map(key=>{const series=session.metricSeries[key];return `<div><span>${series.name}</span><strong>${fullMetric(series.values[index],series)}</strong></div>`;}).join(''),concurrent=session.reviewItems.filter(item=>toMinutes(item.startTime)<=minute&&toMinutes(item.endTime)>=minute),product=concurrent.find(item=>item.productId)?.productId||concurrent.find(item=>item.id==='product-context')?.current?.replace('讲解中','')||'';return `<time>${time}</time>${metrics}${concurrent.length?`<section><small>同期信息</small>${concurrent.map(item=>`<span>${item.type==='opportunity'?'★':item.type==='event'?'◆':'●'} ${item.title}</span>`).join('')}${product?`<span>当前商品：${product}</span>`:''}</section>`:'<small>该分钟无复盘项或运营事件</small>'}`;}
function bindTimelineChart(root,session){const stage=$('[data-time-stage]',root),plot=$('[data-chart-plot]',root),hit=$('[data-chart-hit]',root),cursor=$('[data-time-cursor]',root);if(!stage||!plot||!hit||!cursor)return;const update=index=>{cursorIndex=Math.max(0,Math.min(session.minuteTimeline.length-1,index));const stageRect=stage.getBoundingClientRect(),plotRect=plot.getBoundingClientRect(),left=plotRect.left-stageRect.left+cursorIndex/(session.minuteTimeline.length-1)*plotRect.width,top=plotRect.top-stageRect.top;cursor.hidden=false;cursor.style.left=`${left}px`;cursor.style.top=`${top}px`;cursor.style.height=`${stage.scrollHeight-top}px`;$('[data-cursor-tooltip]',cursor).innerHTML=cursorContent(session,cursorIndex);cursor.classList.toggle('align-right',left>stageRect.width*.72);};const indexFromEvent=event=>{const rect=plot.getBoundingClientRect(),pct=Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width));return Math.round(pct*(session.minuteTimeline.length-1));};hit.addEventListener('pointermove',event=>{if(!cursorLocked)update(indexFromEvent(event));});hit.addEventListener('pointerleave',()=>{if(!cursorLocked)cursor.hidden=true;});hit.addEventListener('click',event=>{if(cursorLocked){cursorLocked=false;cursor.hidden=true;}else{cursorLocked=true;update(indexFromEvent(event));}});if(cursorLocked&&cursorIndex!==null)requestAnimationFrame(()=>update(cursorIndex));}
function bindEnded(root,s){
  $$('[data-timeline-item]',root).forEach(button=>button.addEventListener('click',()=>{activeItemId=button.dataset.timelineItem;const item=s.reviewItems.find(i=>i.id===activeItemId),fallback=item?.type==='event'?s.reviewItems.find(i=>item.relatedItemIds.includes(i.id)&&i.type!=='event')?.id:null,target=item?.detailTargetId||fallback||activeItemId;(viewed[currentKey]||(viewed[currentKey]=new Set())).add(target);renderCockpitReview();}));
  $$('[data-timeline-filter]',root).forEach(button=>button.addEventListener('click',()=>{timelineFilter=button.dataset.timelineFilter;const visible=filteredBusinessItems(s);if(!visible.some(item=>item.id===activeItemId))activeItemId=visible.sort((a,b)=>toMinutes(a.startTime)-toMinutes(b.startTime))[0]?.id||null;renderCockpitReview();}));
  $$('[data-status-filter]',root).forEach(button=>button.addEventListener('click',()=>{statusFilter=button.dataset.statusFilter===statusFilter&&statusFilter!=='all'?'all':button.dataset.statusFilter;const visible=filteredBusinessItems(s);if(!visible.some(item=>item.id===activeItemId))activeItemId=visible.sort((a,b)=>toMinutes(a.startTime)-toMinutes(b.startTime))[0]?.id||null;renderCockpitReview();}));
  $$('[data-metric-key]',root).forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.metricKey;if(selectedMetrics.includes(key)){if(selectedMetrics.length===1){toast('至少保留1项指标');return;}selectedMetrics=selectedMetrics.filter(value=>value!==key);}else{if(selectedMetrics.length>=2){toast('最多同时查看2项指标，请先取消一个。');return;}selectedMetrics=[...selectedMetrics,key];}cursorLocked=false;cursorIndex=null;renderCockpitReview();}));
  $('[data-show-related]',root)?.addEventListener('click',()=>{const item=selectedBusiness(s);if(item?.relatedMetrics?.length){selectedMetrics=item.relatedMetrics.slice(0,2);cursorLocked=false;cursorIndex=null;renderCockpitReview();toast('已切换为当前复盘项的关联指标');}});
  bindTimelineChart(root,s);
  $('[data-start-recording]',root)?.addEventListener('click',startRecording);bindTalk(root);
  $('[data-reset-demo]',root)?.addEventListener('click',resetDemoData);
  $('[data-view-review-recording]',root)?.addEventListener('click',()=>{const formal=sessionFormalRecord(s);openModal('复盘录音','<div class="qj-alert"><span class="qj-alert__icon">i</span><div class="qj-alert__content"><div class="qj-alert__title">录音与ASR已归档</div><div class="qj-alert__description">正式数据中按 session_id 读取原录音、说话人和时间戳。</div></div></div>',formal?.duration||'录音已归档');});
  $$('[data-view-formal]',root).forEach(button=>button.addEventListener('click',()=>{const formal=sessionFormalRecord(s);openModal(button.dataset.viewFormal==='host'?'主播复盘报告':'运营复盘正文',`<div class="qj-report">${button.dataset.viewFormal==='host'?formal.hostHtml:formal.operatorHtml}</div>`,`保存于 ${formal.savedAt}`);}));
  $('[data-show-transcript]',root)?.addEventListener('click',()=>openModal('复盘录音转写','<div class="qj-alert"><span class="qj-alert__icon">i</span><div>演示ASR全文。正式实现会保存说话人、时间戳与原始文本。</div></div>',formatTime(recordingSeconds)));
  $('[data-save-formal]',root)?.addEventListener('click',()=>{const map=JSON.parse(localStorage.getItem(FORMAL_KEY)||'{}'),now=new Date(),reviewedIds=[...(viewed[currentKey]||new Set())];map[currentKey]={sessionKey:currentKey,operatorHtml:$('[data-draft]',root).innerHTML,hostHtml:s.hostReport,tasks:s.tasks,reviewedItemIds:reviewedIds,savedAt:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')} ${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`,duration:formatTime(recordingSeconds)};localStorage.setItem(FORMAL_KEY,JSON.stringify(map));sessionStages[currentKey]='home';demoSessions[currentKey].reviewStatus='completed';endedStage='home';renderCockpitReview();toast('正式复盘正文已保存，场次已转为已复盘');});
}

function snapshot(s){const items=businessItems(s);return `<div class="qj-description"><div class="qj-description__item"><div class="qj-description__label">直播时长</div><div class="qj-description__value">${s.info.duration}</div></div><div class="qj-description__item"><div class="qj-description__label">复盘项</div><div class="qj-description__value">${items.length}项</div></div><div class="qj-description__item"><div class="qj-description__label">主播</div><div class="qj-description__value">${s.info.host}</div></div></div><table class="qj-table"><thead><tr><th class="qj-table__cell">类型</th><th class="qj-table__cell">复盘内容</th><th class="qj-table__cell">本次数据</th></tr></thead><tbody>${items.map(i=>`<tr><td class="qj-table__cell">${itemTypeLabel(i.type)}</td><td class="qj-table__cell">${i.title}</td><td class="qj-table__cell">${i.current} · ${i.difference}</td></tr>`).join('')}</tbody></table>`;}
function tasksHtml(tasks){return tasks.map((t,i)=>`<article class="qj-task" data-task><label><span class="qj-field__label">任务内容</span><input class="qj-input" data-task-content value="${t.task}"></label><label><span class="qj-field__label">负责人</span><input class="qj-input" data-task-owner value="${t.owner}" placeholder="录音未明确则为空"></label><label><span class="qj-field__label">截止时间</span><input class="qj-input" data-task-deadline value="${t.deadline}" placeholder="录音未明确则为空"></label><label><span class="qj-field__label">状态</span><select class="qj-select" data-task-status><option>待完成</option><option>已完成</option></select></label></article>`).join('');}
function renderReview(){const root=$('[data-formal-review-page]');if(!root)return;const s=demoSessions[currentKey],taskMap=JSON.parse(localStorage.getItem(TASK_KEY)||'{}'),saved=sessionFormalRecord(s);const operator=saved?.operatorHtml||reportHtml(s,[],true),host=saved?.hostHtml||s.hostReport,tasks=taskMap[currentKey]||saved?.tasks||s.tasks,duration=saved?.duration||'演示录音',time=saved?.savedAt||'尚未从下播页保存';root.innerHTML=`<div class="qj-column-settings" hidden></div><header class="qj-page__header"><div><h1 class="qj-page__title">直播复盘</h1><div class="qj-page__meta">${currentShop.name} · ${s.info.title} · ${s.info.date} ${s.info.start}–${s.info.end}</div></div><div class="qj-page__actions">${demoPicker()}<span class="qj-status ${saved?'is-success':'is-warning'}"><span class="qj-status__dot"></span><span>${saved?'复盘已完成':'演示预览'} · ${time}</span></span><button class="qj-button qj-button--outline" data-review-recording>查看复盘录音</button></div></header><section class="qj-card"><div class="qj-tabs" role="tablist"><button class="qj-tabs__tab" role="tab" aria-selected="true" aria-controls="panel-operator">运营复盘正文</button><button class="qj-tabs__tab" role="tab" aria-selected="false" aria-controls="panel-host">主播复盘报告</button></div><div id="panel-operator" class="qj-card__body" role="tabpanel"><div class="qj-alert"><span class="qj-alert__icon">i</span><div>${saved?'直接读取下播复盘中保存的正式正文；编辑保存更新同一版本。':'尚未完成本场保存，当前为数据配置生成的演示预览。'}</div></div><div class="qj-rich-text"><div contenteditable="true" data-operator-editor>${operator}</div></div></div><div id="panel-host" class="qj-card__body" role="tabpanel" hidden><div class="qj-report">${host}</div></div></section><section class="qj-card qj-section-gap"><div class="qj-card__header"><div><h2 class="qj-card__title">下场任务</h2><div class="qj-card__meta">没有明确负责人或时间时保持为空</div></div><button class="qj-button qj-button--outline" data-save-tasks>保存任务</button></div><div class="qj-card__body qj-stack">${tasksHtml(tasks)}</div></section><details class="qj-card qj-disclosure"><summary class="qj-card__header"><div><h2 class="qj-card__title">本场数据快照</h2><div class="qj-card__meta">默认折叠</div></div><span>展开</span></summary><div class="qj-card__body">${snapshot(s)}</div></details><footer class="qj-page__footer"><a class="qj-button qj-button--outline" href="live.html?mode=review">返回下播复盘</a><button class="qj-button qj-button--primary" data-save-review>保存复盘正文</button></footer>`;bindSessionSelect(root);bindReview(root,s,saved,duration);}
function bindReview(root,s,saved,duration){$$('[role="tab"]',root).forEach(t=>t.addEventListener('click',()=>{$$('[role="tab"]',root).forEach(x=>x.setAttribute('aria-selected',String(x===t)));$$('[role="tabpanel"]',root).forEach(p=>p.hidden=p.id!==t.getAttribute('aria-controls'));}));$('[data-review-recording]',root).addEventListener('click',()=>{const m=$('#evidence-modal');$('[data-modal-title]',m).textContent='复盘录音与转写';$('[data-modal-time]',m).textContent=duration;$('[data-modal-summary]',m).textContent='ASR全文按原始顺序保存；正文读取同一正式版本。';m.hidden=false;m.setAttribute('aria-hidden','false');});$('[data-save-review]',root).addEventListener('click',()=>{const map=JSON.parse(localStorage.getItem(FORMAL_KEY)||'{}'),now=new Date();map[currentKey]={sessionKey:currentKey,operatorHtml:$('[data-operator-editor]',root).innerHTML,hostHtml:s.hostReport,tasks:collectTasks(root),savedAt:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')} ${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`,duration:saved?.duration||duration};localStorage.setItem(FORMAL_KEY,JSON.stringify(map));toast('正式正文已更新，不触发AI重写');renderReview();});$('[data-save-tasks]',root).addEventListener('click',()=>{const taskMap=JSON.parse(localStorage.getItem(TASK_KEY)||'{}');taskMap[currentKey]=collectTasks(root);localStorage.setItem(TASK_KEY,JSON.stringify(taskMap));toast('任务已按独立对象保存；未生成新的正式正文');});}
function collectTasks(root){return $$('[data-task]',root).map(r=>({task:$('[data-task-content]',r).value.trim(),owner:$('[data-task-owner]',r).value.trim(),deadline:$('[data-task-deadline]',r).value.trim(),status:$('[data-task-status]',r).value}));}
function initMenu(){ $$('[data-menu-toggle]').forEach(b=>b.addEventListener('click',()=>{const g=b.closest('.qj-menu__group'),c=$('.qj-menu__children',g),on=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!on));if(c)c.hidden=on;})); }
function initModalClose(){ $$('[data-close-modal]').forEach(b=>b.addEventListener('click',closeModal)); }
function initEvidenceModal(){ $$('[data-open-evidence]').forEach(button=>button.addEventListener('click',()=>{const modal=$(`#${button.dataset.openEvidence}`);if(!modal)return;$('[data-modal-title]',modal).textContent=button.dataset.title;$('[data-modal-time]',modal).textContent=button.dataset.time;$('[data-modal-summary]',modal).textContent=button.dataset.summary;modal.hidden=false;modal.setAttribute('aria-hidden','false');})); }
function initStaticTabs(){ $$('[data-cockpit-live] [role="tab"][aria-controls]').forEach(tab=>tab.addEventListener('click',()=>{const group=tab.closest('[role="tablist"]'),scope=group.closest('.qj-card');$$('[role="tab"]',group).forEach(item=>{const selected=item===tab;item.setAttribute('aria-selected',String(selected));item.tabIndex=selected?0:-1;});$$('[role="tabpanel"]',scope).forEach(panel=>panel.hidden=panel.id!==tab.getAttribute('aria-controls'));})); }
function initStateSwitch(){const select=$('[data-state-switch]');if(!select)return;const set=value=>{$('[data-success-view]').hidden=value!=='success';$$('[data-view-state]').forEach(v=>v.hidden=v.dataset.viewState!==value);};select.addEventListener('change',e=>set(e.target.value));$$('[data-retry]').forEach(b=>b.addEventListener('click',()=>{select.value='success';set('success');toast('数据已恢复');}));}

document.addEventListener('DOMContentLoaded',()=>{if($('[data-ended-app]'))location.replace('live.html?mode=review');if($('[data-formal-review-page]'))renderReview();if($('[data-cockpit-app]')){$$('[data-cockpit-mode]').forEach(button=>button.addEventListener('click',()=>setCockpitMode(button.dataset.cockpitMode)));setCockpitMode(cockpitMode);}initMenu();initModalClose();initEvidenceModal();initStaticTabs();initStateSwitch();$('[data-stop-recording]')?.addEventListener('click',stopRecording);});
